import React, { useState, useEffect, useRef } from 'react';
import { 
  Layout, 
  FileText, 
  Upload, 
  Sparkles, 
  ChevronDown, 
  Image as ImageIcon, 
  PenTool, 
  Download,
  ArrowRight,
  CheckCircle2,
  Palette,
  MonitorPlay,
  X,
  UserCircle2,
  Check,
  Loader2,
  AlertCircle,
  Users,
  Plus,
  Wand2,
  Trash2,
  Globe,
  Key,          // Added Key icon
  Eye,          // Added Eye icon
  EyeOff,       // Added EyeOff icon
  ExternalLink, // Added ExternalLink icon
  Save          // Added Save icon
} from 'lucide-react';

// --- Translations ---
const TRANSLATIONS = {
  zh: {
    appTitle: "简报架构生成器",
    apiKeyLabel: "Google Gemini API Key",
    apiKeyPlaceholder: "在此贴上您的 API Key (以 AIza 开头...)",
    apiKeyHelp: "还没有 Key？",
    getKeyLink: "去 Google AI Studio 免费申请",
    apiKeySaved: "API Key 已保存",
    apiKeyRequired: "请先输入 API Key 才能开始生成",
    selectStyleTitle: "选择您的简报风格，让AI为您量身打造简报架构",
    stylePresetsTitle: "常用风格快选",
    designStyleLabel: "设计风格与指令",
    designStylePlaceholder: "请描述您想要的设计风格，或点击上方按钮快速选择...",
    includePersona: "融合特定设定：融入个人形象",
    includePersonaDesc: "✨ AI 将会在每一页自动预留“讲解员”空间，并调整构图避免遮挡。",
    targetAudience: "目标受众 (Target Audience)",
    targetAudiencePlaceholder: "例如：初中学生、潜在投资人、公司高层管理...",
    pageCount: "预计页数",
    contentLabel: "内容文本 / 资料贴上",
    contentPlaceholder: "请贴上您的演讲稿、文章内容或大纲。AI 将以此生成简报结构...",
    uploadLabel: "上传参考图片或 PDF (选填)",
    uploadButton: "选择档案 (图片/PDF)",
    uploadHint: "提示：如果是图片，AI 也可提取核心重点并分析视觉风格！",
    generateButton: "开始分析与生成简报",
    generating: "正在呼叫 Gemini API...",
    generatingDesc: "正在分析文本、解析风格并规划简报架构",
    resultTitle: "Gemini 生成结果",
    downloadButton: "下载文字档 (.txt)",
    corePoints: "核心重点",
    corePointsPlaceholder: "输入核心重点...",
    visualElements: "视觉元素",
    visualElementsPlaceholder: "输入视觉元素描述...",
    layoutDesign: "排版设计",
    layoutDesignPlaceholder: "输入排版设计指南...",
    addPage: "新增页面 (Add Page)",
    deleteConfirm: "确认删除?",
    pageTitlePlaceholder: "请输入标题 (例如: 市场分析)...",
    aiGenerateButton: "AI 自动生成内容",
    generatingButton: "生成中...",
    enterTitleWarning: "请输入标题!",
    footerText: "@ 2026 Designed by Wei Wen. All rights reserved",
    generatedByGemini: "Generated by Gemini",
    styleSettingApplied: "此设定已由 Gemini 优化并应用于下列所有页面的设计与 AI 生图指令中"
  },
  en: {
    appTitle: "Presentation Outline Generator",
    apiKeyLabel: "Google Gemini API Key",
    apiKeyPlaceholder: "Paste your API Key here (starts with AIza...)",
    apiKeyHelp: "Don't have a key?",
    getKeyLink: "Get one free at Google AI Studio",
    apiKeySaved: "API Key Saved",
    apiKeyRequired: "Please enter API Key to start",
    selectStyleTitle: "Select your style, let AI build your presentation structure",
    stylePresetsTitle: "Quick Style Presets",
    designStyleLabel: "Design Style & Instructions",
    designStylePlaceholder: "Describe your desired style or select from above...",
    includePersona: "Integrate Persona Setting",
    includePersonaDesc: "✨ AI will reserve space for a 'presenter' on every page and adjust composition.",
    targetAudience: "Target Audience",
    targetAudiencePlaceholder: "E.g., Junior students, Potential Investors, C-Level Execs...",
    pageCount: "Estimated Pages",
    contentLabel: "Content Text / Paste Data",
    contentPlaceholder: "Paste your speech, article, or outline here. AI will structure it...",
    uploadLabel: "Upload Reference Image or PDF (Optional)",
    uploadButton: "Choose File (Image/PDF)",
    uploadHint: "Tip: AI can extract core points from images and analyze visual style!",
    generateButton: "Analyze & Generate Presentation",
    generating: "Calling Gemini API...",
    generatingDesc: "Analyzing text, parsing style, and planning structure...",
    resultTitle: "Gemini Result",
    downloadButton: "Download Text (.txt)",
    corePoints: "Core Points",
    corePointsPlaceholder: "Enter core points...",
    visualElements: "Visual Elements",
    visualElementsPlaceholder: "Enter visual element description...",
    layoutDesign: "Layout Design",
    layoutDesignPlaceholder: "Enter layout instructions...",
    addPage: "Add Page",
    deleteConfirm: "Confirm Delete?",
    pageTitlePlaceholder: "Enter title (e.g., Market Analysis)...",
    aiGenerateButton: "AI Generate Content",
    generatingButton: "Generating...",
    enterTitleWarning: "Enter Title!",
    footerText: "@ 2026 Designed by Wei Wen. All rights reserved",
    generatedByGemini: "Generated by Gemini",
    styleSettingApplied: "This setting has been optimized by Gemini and applied to all pages below."
  }
};

// --- Style Presets with Language Support ---
const GET_STYLE_PRESETS = (lang) => {
  if (lang === 'en') {
    return [
      { id: 1, label: "Ghibli Natural", value: "Ghibli animation style, high saturation blue sky and white clouds, lush green vegetation, hand-painted watercolor texture, creating a fresh, healing, and grand natural atmosphere." },
      { id: 2, label: "Game Quest Map", value: "ISO 2.5D perspective, game UI interface elements, quest node path, sense of adventure and exploration, pixel or vector style." },
      { id: 3, label: "Comic/Manga", value: "Black and white or pop colors, using speech bubbles, speed lines, bold characters to emphasize keywords, strong visual impact." },
      { id: 4, label: "Watercolor", value: "Water stains, transparency, soft edges, artistic atmosphere, suitable for expressing literary and emotional themes." },
      { id: 5, label: "Pastel", value: "Low saturation macaron colors (pink, mint green, light purple), dreamy, light, and cute visual experience." },
      { id: 6, label: "Hand-drawn", value: "Warm and friendly, using hand-drawn style icons and borders, lively colors, natural and unrestrained lines." },
      { id: 7, label: "Warm & Healing", value: "Earth tones (beige, brown), soft rounded corners, natural textures, creating a relaxed and trusting atmosphere." },
      { id: 8, label: "Japanese Realistic", value: "Minimalist, whitespace, high-quality real scene photography, wood tones, emphasizing details and reality, clean like Muji." },
      { id: 9, label: "Retro Nostalgic", value: "Low-fi texture, noise, 80s/90s color scheme, retro serif fonts, old newspaper or film filter effects." },
      { id: 10, label: "Playful & Childlike", value: "High saturation primary colors (red, yellow, blue), simple geometric shapes, doodle style, full of vitality and fun." },
      { id: 11, label: "Natural Organic", value: "Using recycled paper texture, plant elements, dark green and earthy yellow, emphasizing environmental protection, sustainability, and connection with nature." },
      { id: 12, label: "Cyberpunk", value: "High contrast neon colors (purple, cyan, magenta), dark background, Glitch Art, decadent aesthetics of technology and future." },
      { id: 13, label: "Flat Design", value: "No shadows, bright solid color blocks, simple vector icons, modern UI style, clear and efficient information transmission." },
    ];
  }
  return [
    { id: 1, label: "吉卜力自然风 (Ghibli Natural)", value: "吉卜力动画风格，高饱和度的蓝天白云、茂密的绿色植被、手绘水彩质感，营造清新、治愈、宏大的自然氛围。" },
    { id: 2, label: "游戏任务地图 (Game Quest Map)", value: "ISO 2.5D 视角，游戏 UI 界面元素，任务节点路径，冒险与探索感，像素或矢量风格。" },
    { id: 3, label: "漫画风格（突出生字） (Comic/Manga)", value: "黑白或波普色彩，使用对话气泡、速度线、粗体大字强调关键词，视觉冲击力强。" },
    { id: 4, label: "水彩风格 (Watercolor)", value: "水痕晕染、透明感、柔和的边缘、艺术气息，适合表现文艺、感性的主题。" },
    { id: 5, label: "粉彩风格 (Pastel)", value: "低饱和度的马卡龙色系（粉红、薄荷绿、淡紫），梦幻、轻盈、可爱的视觉感受。" },
    { id: 6, label: "手绘插画 (Hand-drawn)", value: "温暖亲切，使用手绘风格的图标与边框，色彩活泼，线条自然不拘束。" },
    { id: 7, label: "温暖疗愈 (Warm & Healing)", value: "大地色系（米色、棕色）、柔和的圆角、自然纹理，营造放松与信任的氛围。" },
    { id: 8, label: "日式写实 (Japanese Realistic)", value: "极简、留白、高品质实景摄影、木质色调，强调细节与真实感，由于无印良品般的干净。" },
    { id: 9, label: "复古怀旧 (Retro Nostalgic)", value: "低保真 (Lo-fi) 质感、噪点、80/90 年代配色、复古衬线字体，旧报纸或胶片滤镜效果。" },
    { id: 10, label: "活泼童趣 (Playful & Childlike)", value: "高饱和三原色（红黄蓝），简单的几何图形，涂鸦风格，充满活力与趣味。" },
    { id: 11, label: "自然有机 (Natural Organic)", value: "使用再生纸纹理、植物元素、墨绿色与土黄色，强调环保、可持续与自然连结。" },
    { id: 12, label: "赛博庞克 (Cyberpunk)", value: "高对比度霓虹色（紫、青、品红），深色背景，故障艺术 (Glitch Art)，科技与未来的颓废美学。" },
    { id: 13, label: "扁平化设计 (Flat Design)", value: "无阴影、明亮的纯色色块、简洁的矢量图标，现代 UI 风格，信息传达清晰高效。" },
  ];
};

// --- Helper: Convert File to Base64 for Gemini Multimodal ---
const fileToBase64 = (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result.split(',')[1]);
    reader.onerror = error => reject(error);
  });
};

// --- Helper: Normalize Content to String ---
const normalizeContent = (content) => {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.map(item => typeof item === 'string' ? item : JSON.stringify(item)).join('\n');
  if (typeof content === 'object' && content !== null) return JSON.stringify(content);
  if (content === undefined || content === null) return "";
  return String(content);
};

// --- API Call Logic: Generate Full Presentation ---
const generateWithGemini = async (config, language, apiKey) => {
  const { styleDesc, pageCount, content, uploadedFile, includePersona, targetAudience } = config;

  if (!apiKey) throw new Error("API Key Missing");

  const langInstruction = language === 'en' ? 'English' : 'Simplified Chinese (简体中文)';

  const systemPrompt = `
    You are a professional Presentation Designer and AI Art Director.
    Your task is to generate a structured outline for a presentation based on the user's input.
    
    Output MUST be valid JSON with this structure:
    {
      "topic": "Creative Main Title",
      "globalStyle": {
        "title": "Style Name",
        "content": "Detailed description of colors, fonts, and mood."
      },
      "pages": [
        {
          "page": 1,
          "title": "Page Title",
          "corePoints": "Key content points (bullet points preferred). IMPORTANT: If a file (PDF or Image) is uploaded, this MUST be extracted directly from the document's core points.",
          "visualElements": "Description of visual elements, icons, illustrations, or charts in ${langInstruction}.",
          "layoutDesign": "Specific layout instructions"
        }
      ]
    }

    CONSTRAINTS:
    1. Generate exactly ${pageCount} pages.
    2. Language: ALL JSON values must be in ${langInstruction}.
    3. Style: Adapt to user's style description: "${styleDesc}".
    4. Persona Mode: ${includePersona ? "ENABLED. Crucial: In 'layoutDesign', you MUST explicitly mention reserving space (e.g., side panel or corner) for a presenter avatar/photo. In 'visualElements', mention that the composition should allow space for a character overlay." : "DISABLED."}
    5. Target Audience: "${targetAudience || "General Audience"}". Adjust the tone, complexity, and visual style to suit this audience perfectly.
    6. Content Source: Use this context: "${content}". 
    ${uploadedFile ? "7. FILE UPLOADED: Use the attached file as the PRIMARY source of truth. Extract key arguments, data points, and structure from it." : "If content is empty, invent a creative topic based on the style."}
  `;

  let contents = [];
  
  if (uploadedFile) {
    const fileBase64 = await fileToBase64(uploadedFile);
    const isImage = uploadedFile.type.startsWith('image/');
    const fileInstruction = isImage 
        ? "CRITICAL TASK: Analyze this uploaded image in two aspects: 1. CONTENT EXTRACTION: Read and extract all visible text, charts, or diagrams to use as the core information source for the presentation (function as OCR). 2. STYLE ANALYSIS: Analyze its visual style/art direction and incorporate it into the 'globalStyle' and 'layoutDesign'."
        : "CRITICAL TASK: Read the attached document carefully. Extract the most important core points, logic, and data to structure the presentation. Do not hallucinate information not present in the text.";

    contents = [{
      parts: [
        { text: systemPrompt },
        { text: fileInstruction },
        { inlineData: { mimeType: uploadedFile.type, data: fileBase64 } }
      ]
    }];
  } else {
    contents = [{ parts: [{ text: systemPrompt }] }];
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: contents,
          generationConfig: { responseMimeType: "application/json" }
        })
      }
    );

    if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error?.message || 'API Request Failed');
    }
    const data = await response.json();
    const generatedText = data.candidates[0].content.parts[0].text;
    const parsedData = JSON.parse(generatedText);

    // Sanitize Response Data
    if (parsedData.globalStyle) {
        parsedData.globalStyle.content = normalizeContent(parsedData.globalStyle.content);
    }
    if (Array.isArray(parsedData.pages)) {
        parsedData.pages = parsedData.pages.map(page => ({
            ...page,
            title: normalizeContent(page.title),
            corePoints: normalizeContent(page.corePoints),
            visualElements: normalizeContent(page.visualElements),
            layoutDesign: normalizeContent(page.layoutDesign)
        }));
    }

    return parsedData;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

// --- API Call Logic: Generate Single Page Content ---
const generatePageContent = async (config, pageTitle, currentTopic, globalStyle, language, apiKey) => {
  const { styleDesc, targetAudience, includePersona } = config;
  const langInstruction = language === 'en' ? 'English' : 'Simplified Chinese (简体中文)';

  if (!apiKey) throw new Error("API Key Missing");

  const systemPrompt = `
    You are a professional Presentation Designer.
    The user is adding a NEW SLIDE to an existing presentation.
    
    CONTEXT:
    - Presentation Topic: "${currentTopic}"
    - Target Audience: "${targetAudience || "General Audience"}"
    - Global Style: "${globalStyle.title}" (${globalStyle.content})
    - User Style Preference: "${styleDesc}"
    - Persona Mode: ${includePersona ? "ENABLED" : "DISABLED"}

    TASK:
    Generate content for a single slide with the specific title: "${pageTitle}".

    Output MUST be valid JSON with this structure:
    {
      "corePoints": "Key content points (bullet points preferred) relevant to the title '${pageTitle}'.",
      "visualElements": "Description of visual elements in ${langInstruction}, consistent with the Global Style.",
      "layoutDesign": "Specific layout instructions, consistent with the Global Style.${includePersona ? " MUST reserve space for presenter." : ""}"
    }

    CONSTRAINTS:
    1. Language: ${langInstruction}.
    2. Tone: Match the target audience.
  `;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: systemPrompt }] }],
          generationConfig: { responseMimeType: "application/json" }
        })
      }
    );

    if (!response.ok) throw new Error('API Request Failed');
    const data = await response.json();
    const generatedText = data.candidates[0].content.parts[0].text;
    const parsedData = JSON.parse(generatedText);

    return {
        corePoints: normalizeContent(parsedData.corePoints),
        visualElements: normalizeContent(parsedData.visualElements),
        layoutDesign: normalizeContent(parsedData.layoutDesign)
    };

  } catch (error) {
    console.error("Gemini Page Gen Error:", error);
    throw error;
  }
};

// --- Components ---

const Header = ({ language, setLanguage, t }) => (
  <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-violet-600 rounded-xl flex items-center justify-center shadow-lg shadow-violet-200">
          <MonitorPlay className="text-white w-6 h-6" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight hidden md:block">{t.appTitle}</h1>
          <h1 className="text-lg font-bold text-slate-900 tracking-tight md:hidden">Gemini Slides</h1>
          <div className="flex items-center gap-1">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
            </span>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Powered by Gemini ✨</span>
          </div>
        </div>
      </div>
      
      {/* Language Toggle */}
      <button 
        onClick={() => setLanguage(prev => prev === 'zh' ? 'en' : 'zh')}
        className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-slate-100 transition-colors border border-transparent hover:border-slate-200"
      >
        <Globe className="w-4 h-4 text-slate-500" />
        <span className="text-sm font-medium text-slate-700">
            {language === 'zh' ? 'English' : '中文'}
        </span>
      </button>
    </div>
  </header>
);

const ApiKeyInput = ({ apiKey, setApiKey, t }) => {
    const [showKey, setShowKey] = useState(false);
    
    return (
        <div className="bg-violet-50 border border-violet-100 rounded-2xl p-6 mb-8 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-violet-200 rounded-full blur-3xl opacity-30 -mr-10 -mt-10"></div>
            
            <div className="relative z-10">
                <div className="flex items-center justify-between mb-4">
                    <label className="flex items-center gap-2 text-sm font-bold text-violet-900">
                        <Key className="w-4 h-4 text-violet-600" />
                        {t.apiKeyLabel}
                    </label>
                    <a 
                        href="https://aistudio.google.com/app/apikey" 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="text-xs font-medium text-violet-600 hover:text-violet-800 flex items-center gap-1 hover:underline"
                    >
                        {t.apiKeyHelp} {t.getKeyLink}
                        <ExternalLink className="w-3 h-3" />
                    </a>
                </div>
                
                <div className="relative">
                    <input
                        type={showKey ? "text" : "password"}
                        value={apiKey}
                        onChange={(e) => setApiKey(e.target.value)}
                        placeholder={t.apiKeyPlaceholder}
                        className="w-full pl-4 pr-24 py-3 bg-white border border-violet-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-transparent outline-none transition-all shadow-sm font-mono text-sm"
                    />
                    <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
                        <button
                            onClick={() => setShowKey(!showKey)}
                            className="p-2 text-slate-400 hover:text-violet-600 hover:bg-violet-50 rounded-lg transition-colors"
                            type="button"
                        >
                            {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                        </button>
                    </div>
                </div>
                {apiKey && apiKey.startsWith("AIza") && (
                     <div className="mt-2 flex items-center gap-1.5 text-xs text-green-600 font-medium animate-fade-in">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        {t.apiKeySaved}
                     </div>
                )}
            </div>
        </div>
    );
};

const InputStep = ({ config, updateConfig, onGenerate, isGenerating, t, language, apiKey, setApiKey }) => {
  const fileInputRef = useRef(null);
  const stylePresets = GET_STYLE_PRESETS(language);

  const handleFileClick = () => {
    fileInputRef.current.click();
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      updateConfig('uploadedFile', file);
    }
  };

  const clearFile = (e) => {
      e.stopPropagation();
      updateConfig('uploadedFile', null);
      if (fileInputRef.current) {
          fileInputRef.current.value = "";
      }
  };

  const isButtonDisabled = isGenerating || !apiKey || apiKey.length < 10;

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 animate-fade-in">
      
      {/* API Key Input Section - New Addition */}
      <ApiKeyInput apiKey={apiKey} setApiKey={setApiKey} t={t} />

      <div className="bg-white rounded-3xl shadow-xl shadow-slate-200/50 p-8 border border-white relative overflow-hidden">
        {isGenerating && (
            <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center">
                 <Loader2 className="w-12 h-12 text-violet-600 animate-spin mb-4" />
                 <h3 className="text-xl font-bold text-slate-800">✨ Gemini {language === 'zh' ? '正在思考中...' : 'is thinking...'}</h3>
                 <p className="text-slate-500">{t.generatingDesc}</p>
            </div>
        )}

        <div className="mb-8 pb-6 border-b border-slate-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-violet-100 rounded-xl flex items-center justify-center text-violet-600 shrink-0">
             <FileText className="w-6 h-6" />
          </div>
          <h2 className="text-xl font-bold text-slate-800">{t.selectStyleTitle}</h2>
        </div>

        <div className="space-y-8">
            <div>
                 <label className="block text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-violet-500" />
                    {t.stylePresetsTitle}
                 </label>
                 <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                    {stylePresets.map((style) => (
                        <button
                        key={style.id}
                        onClick={() => updateConfig('styleDesc', style.value)}
                        className={`text-left p-3 border rounded-xl transition-all group h-full flex flex-col justify-between ${
                            config.styleDesc === style.value 
                            ? 'bg-violet-50 border-violet-500 shadow-sm ring-1 ring-violet-500' 
                            : 'bg-slate-50 border-slate-200 hover:border-violet-300 hover:bg-violet-50'
                        }`}
                        >
                        <span className={`text-xs font-bold ${config.styleDesc === style.value ? 'text-violet-700' : 'text-slate-700 group-hover:text-violet-700'}`}>
                            {style.label}
                        </span>
                        </button>
                    ))}
                 </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">{t.designStyleLabel}</label>
              <textarea
                value={config.styleDesc}
                onChange={(e) => updateConfig('styleDesc', e.target.value)}
                placeholder={t.designStylePlaceholder}
                className="w-full h-24 p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-violet-500 focus:bg-white transition-all resize-none shadow-inner"
              />
            </div>
            
            {/* 个人形象融合设定 */}
            <div 
                onClick={() => updateConfig('includePersona', !config.includePersona)}
                className={`flex items-start gap-4 p-5 rounded-xl border cursor-pointer transition-all duration-200 ${
                    config.includePersona 
                    ? 'bg-violet-50 border-violet-200 shadow-sm' 
                    : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                }`}
            >
                <div className={`mt-1 flex-shrink-0 w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-colors ${
                    config.includePersona 
                    ? 'bg-violet-600 border-violet-600' 
                    : 'bg-white border-slate-300'
                }`}>
                    {config.includePersona && <Check className="w-4 h-4 text-white stroke-[3]" />}
                </div>
                <div>
                    <div className="flex items-center gap-2 mb-1">
                        <UserCircle2 className={`w-5 h-5 ${config.includePersona ? 'text-violet-600' : 'text-slate-500'}`} />
                        <h4 className={`text-sm font-bold ${config.includePersona ? 'text-violet-900' : 'text-slate-700'}`}>
                            {t.includePersona}
                        </h4>
                    </div>
                    <p className="text-xs text-slate-500 leading-relaxed">
                        {t.includePersonaDesc}
                    </p>
                </div>
            </div>

            {/* 新增：目标受众 */}
            <div>
               <label className="block text-sm font-semibold text-slate-700 mb-2 flex items-center gap-2">
                   <Users className="w-4 h-4 text-violet-500" />
                   {t.targetAudience}
               </label>
               <input 
                  type="text" 
                  value={config.targetAudience || ''}
                  onChange={(e) => updateConfig('targetAudience', e.target.value)}
                  placeholder={t.targetAudiencePlaceholder}
                  className="w-full p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-violet-500 focus:bg-white transition-all shadow-inner"
               />
            </div>

            <div>
               <label className="block text-sm font-semibold text-slate-700 mb-2">{t.pageCount}</label>
               <div className="relative w-32">
                 <input 
                    type="number" 
                    value={config.pageCount}
                    onChange={(e) => updateConfig('pageCount', parseInt(e.target.value) || 1)}
                    min="1"
                    max="20"
                    className="w-full pl-4 pr-4 py-3 bg-slate-50 border-0 rounded-xl font-semibold text-slate-800 focus:ring-2 focus:ring-violet-500"
                 />
               </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">{t.contentLabel}</label>
              <textarea
                value={config.content}
                onChange={(e) => updateConfig('content', e.target.value)}
                placeholder={t.contentPlaceholder}
                className="w-full h-40 p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-violet-500 focus:bg-white transition-all resize-none shadow-inner"
              />
            </div>

            <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">{t.uploadLabel}</label>
                <div className="flex flex-wrap gap-4 items-center">
                    <input 
                        type="file" 
                        ref={fileInputRef}
                        onChange={handleFileChange}
                        className="hidden"
                        accept="image/*,application/pdf"
                    />
                    <button 
                        onClick={handleFileClick}
                        className="flex items-center gap-2 px-6 py-3 bg-white border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-50 hover:border-slate-300 transition-all shadow-sm"
                    >
                        <Upload className="w-5 h-5" />
                        <span>{t.uploadButton}</span>
                    </button>
                    
                    {config.uploadedFile && (
                        <div className="flex items-center gap-2 px-4 py-3 bg-green-50 text-green-700 rounded-xl border border-green-100 animate-fade-in">
                            <CheckCircle2 className="w-4 h-4" />
                            <span className="text-sm font-medium truncate max-w-[200px]">{config.uploadedFile.name}</span>
                            <button 
                                onClick={clearFile}
                                className="ml-1 p-1 hover:bg-green-100 rounded-full transition-colors"
                            >
                                <X className="w-3 h-3 text-green-600" />
                            </button>
                        </div>
                    )}
                </div>
                <p className="mt-2 text-xs text-slate-400 flex items-center gap-1">
                    <Sparkles className="w-3 h-3 text-violet-400" /> 
                    {t.uploadHint}
                </p>
            </div>
        </div>

        <div className="mt-10 pt-6 border-t border-slate-100">
          <button 
            onClick={onGenerate}
            disabled={isButtonDisabled}
            className="w-full bg-violet-600 hover:bg-violet-700 disabled:bg-slate-300 disabled:cursor-not-allowed text-white text-lg font-bold py-4 rounded-xl shadow-lg shadow-violet-200 flex items-center justify-center gap-3 transition-transform hover:scale-[1.01] active:scale-[0.99]"
          >
            {isGenerating ? (
                <>
                    <Loader2 className="w-6 h-6 animate-spin" />
                    {t.generating}
                </>
            ) : (
                <>
                    <Sparkles className="w-6 h-6" />
                    {!apiKey ? t.apiKeyRequired : t.generateButton}
                </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
};

const EditableText = ({ value, onChange, className, isTextarea = false, placeholder }) => {
    const safeValue = normalizeContent(value);

    if (isTextarea) {
        return (
            <textarea
                value={safeValue}
                onChange={(e) => onChange(e.target.value)}
                className={`w-full bg-transparent border border-transparent hover:border-slate-300 focus:border-violet-500 rounded-lg p-2 focus:bg-white focus:ring-0 transition-all outline-none resize-none ${className}`}
                placeholder={placeholder}
                rows={Math.max(3, safeValue.split('\n').length)}
            />
        );
    }
    return (
        <input
            type="text"
            value={safeValue}
            onChange={(e) => onChange(e.target.value)}
            className={`w-full bg-transparent border border-transparent hover:border-slate-300 focus:border-violet-500 rounded-lg px-2 py-1 focus:bg-white focus:ring-0 transition-all outline-none ${className}`}
            placeholder={placeholder}
        />
    );
};

const ResultStep = ({ resultData, setResultData, onReset, config, t, language, apiKey }) => {
  const [generatingPages, setGeneratingPages] = useState({}); 
  const [deleteConfirmIndex, setDeleteConfirmIndex] = useState(null); 
  const [warningIndex, setWarningIndex] = useState(null); 

  const handlePageChange = (index, field, value) => {
    const newPages = [...resultData.pages];
    newPages[index] = { ...newPages[index], [field]: value };
    setResultData({ ...resultData, pages: newPages });
  };
  
  const handleDeletePage = (indexToDelete) => {
    const remainingPages = resultData.pages.filter((_, index) => index !== indexToDelete);
    const reindexedPages = remainingPages.map((page, index) => ({
        ...page,
        page: index + 1
    }));
    setResultData({ ...resultData, pages: reindexedPages });
    setDeleteConfirmIndex(null); 
  };

  const handleGlobalStyleChange = (field, value) => {
      setResultData({
          ...resultData,
          globalStyle: { ...resultData.globalStyle, [field]: value }
      });
  };

  const handleTopicChange = (value) => {
      setResultData({ ...resultData, topic: value });
  };

  const handleAddPage = () => {
    const newPageNum = resultData.pages.length + 1;
    const newPage = {
      page: newPageNum,
      title: "", 
      corePoints: "",
      visualElements: "",
      layoutDesign: ""
    };
    setResultData({
      ...resultData,
      pages: [...resultData.pages, newPage]
    });
  };

  const handleGeneratePageContent = async (index) => {
    const page = resultData.pages[index];
    if (!page.title.trim()) {
        setWarningIndex(index);
        setTimeout(() => setWarningIndex(null), 3000);
        return;
    }

    setGeneratingPages(prev => ({ ...prev, [index]: true }));

    try {
        const generatedContent = await generatePageContent(
            config, 
            page.title, 
            resultData.topic, 
            resultData.globalStyle,
            language,
            apiKey
        );
        
        const newPages = [...resultData.pages];
        newPages[index] = {
            ...newPages[index],
            ...generatedContent
        };
        setResultData({ ...resultData, pages: newPages });
    } catch (error) {
        console.error("Page Gen Error:", error);
        alert("Failed to generate page content. Check API Key.");
    } finally {
        setGeneratingPages(prev => ({ ...prev, [index]: false }));
    }
  };

  const handleDownload = () => {
    let content = `TOPIC: ${resultData.topic}\n\n`;
    content += `=== GLOBAL STYLE ===\n`;
    content += `Title: ${resultData.globalStyle.title}\n`;
    content += `Description: ${resultData.globalStyle.content}\n\n`;
    content += `==================================================\n\n`;

    resultData.pages.forEach((page, index) => {
      content += `Page ${page.page}: ${page.title}\n\n`;
      content += `[${t.corePoints}]\n${page.corePoints}\n\n`;
      content += `[${t.visualElements}]\n${page.visualElements}\n\n`;
      content += `[${t.layoutDesign}]\n${page.layoutDesign}\n\n`;
      content += `--------------------------------------------------\n\n`;
    });

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${resultData.topic.substring(0, 20)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 animate-fade-in-up">
      
      {/* Header Result */}
      <div className="mb-8 flex flex-col md:flex-row md:justify-between md:items-end gap-4">
        <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
                 <Sparkles className="w-4 h-4 text-violet-500" />
                 <div className="text-sm font-bold text-slate-400 uppercase tracking-wider">{t.resultTitle}</div>
            </div>
            <EditableText 
                value={resultData.topic} 
                onChange={handleTopicChange} 
                className="text-3xl font-extrabold text-slate-900 leading-tight"
            />
        </div>
        <button 
            onClick={handleDownload}
            className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg font-medium shadow-md transition-colors whitespace-nowrap"
        >
            <Download className="w-4 h-4" />
            {t.downloadButton}
        </button>
      </div>

      {/* Global Style Card */}
      <div className="bg-slate-900 rounded-2xl p-6 mb-10 shadow-xl border border-slate-800 relative overflow-hidden group">
        <div className="absolute top-0 right-0 w-64 h-64 bg-violet-500 rounded-full blur-[100px] opacity-20 group-hover:opacity-30 transition-opacity"></div>
        <div className="relative z-10">
            <div className="flex items-center gap-2 mb-4 text-violet-300">
                <Palette className="w-5 h-5" />
                <h3 className="font-bold text-lg">{resultData.globalStyle.title}</h3>
            </div>
            <div className="bg-slate-800/50 p-2 rounded-xl border border-slate-700/50 backdrop-blur-sm">
                <EditableText
                    isTextarea
                    value={resultData.globalStyle.content}
                    onChange={(val) => handleGlobalStyleChange('content', val)}
                    className="text-slate-300 leading-relaxed text-sm focus:text-slate-900 focus:bg-white"
                />
            </div>
            <div className="mt-4 text-xs text-slate-500 flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-yellow-500" />
                {t.styleSettingApplied}
            </div>
        </div>
      </div>

      {/* Pages List */}
      <div className="space-y-8">
        {resultData.pages.map((page, index) => (
            <div key={index} className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden hover:shadow-lg transition-shadow duration-300 group">
                {/* Page Header */}
                <div className="px-6 py-4 border-b border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-50/50">
                    <div className="flex items-center gap-3 w-full">
                        <span className="text-2xl font-black text-violet-600 font-mono whitespace-nowrap">Page {page.page}</span>
                        <div className="w-px h-6 bg-slate-300 hidden md:block"></div>
                        <div className="flex-1">
                             <EditableText 
                                value={page.title} 
                                onChange={(val) => handlePageChange(index, 'title', val)}
                                className={`text-xl font-bold transition-colors ${warningIndex === index ? 'text-red-500 placeholder:text-red-300' : 'text-slate-800 placeholder-slate-400'}`}
                                placeholder={warningIndex === index ? t.enterTitleWarning : t.pageTitlePlaceholder}
                             />
                        </div>
                    </div>
                    
                    <div className="flex items-center gap-2">
                        {/* Single Page Generation Button */}
                        <button 
                            onClick={() => handleGeneratePageContent(index)}
                            disabled={generatingPages[index]}
                            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-all whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed ${
                                warningIndex === index 
                                ? 'bg-red-100 text-red-600 animate-pulse' 
                                : 'bg-violet-100 hover:bg-violet-200 text-violet-700'
                            }`}
                            title="根据标题自动生成内容"
                        >
                            {generatingPages[index] ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                            {generatingPages[index] ? t.generatingButton : warningIndex === index ? t.enterTitleWarning : t.aiGenerateButton}
                        </button>
                        
                        {/* Delete Button (Double Click Logic) */}
                        <button
                            onClick={() => {
                                if (deleteConfirmIndex === index) {
                                    handleDeletePage(index);
                                } else {
                                    setDeleteConfirmIndex(index);
                                    setTimeout(() => setDeleteConfirmIndex(null), 3000); // Auto reset
                                }
                            }}
                            className={`p-2 rounded-lg transition-all duration-200 flex items-center gap-2 ${
                                deleteConfirmIndex === index 
                                ? "bg-red-500 text-white hover:bg-red-600 shadow-sm px-3" 
                                : "text-slate-400 hover:text-red-500 hover:bg-red-50"
                            }`}
                            title={deleteConfirmIndex === index ? "Again to Confirm" : "Delete Page"}
                        >
                            <Trash2 className="w-4 h-4" />
                            {deleteConfirmIndex === index && <span className="text-xs font-bold whitespace-nowrap">{t.deleteConfirm}</span>}
                        </button>
                    </div>
                </div>

                <div className="p-6 space-y-6">
                    {/* Core Points (was Summary) */}
                    <div>
                        <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">{t.corePoints}</h4>
                        <div className="bg-slate-50 p-2 rounded-xl border border-slate-100">
                             <EditableText 
                                isTextarea
                                value={page.corePoints} 
                                onChange={(val) => handlePageChange(index, 'corePoints', val)}
                                className="text-slate-700 leading-relaxed text-base min-h-[80px]"
                                placeholder={t.corePointsPlaceholder}
                             />
                        </div>
                    </div>

                    {/* Visual Elements (was Image Prompt) - MOVED TO MIDDLE */}
                    <div className="bg-slate-900 rounded-xl p-3 border border-slate-800">
                         <div className="flex items-center gap-2 mb-2 text-green-400 px-2">
                            <ImageIcon className="w-4 h-4" />
                            <h4 className="font-bold text-xs uppercase tracking-wider flex items-center gap-2">
                                {t.visualElements}
                                <span className="text-[10px] bg-green-800 text-green-200 px-1 rounded">{t.generatedByGemini}</span>
                            </h4>
                        </div>
                        <EditableText 
                            isTextarea
                            value={page.visualElements} 
                            onChange={(val) => handlePageChange(index, 'visualElements', val)}
                            className="text-green-300 font-mono text-sm leading-relaxed break-words focus:text-slate-900 focus:bg-white min-h-[60px]"
                            placeholder={t.visualElementsPlaceholder}
                        />
                    </div>

                    {/* Layout Design (was Layout Guide) - MOVED TO BOTTOM */}
                    <div className="bg-blue-50 rounded-xl p-3 border border-blue-100">
                        <div className="flex items-center gap-2 mb-2 text-blue-700 px-2">
                            <Layout className="w-5 h-5" />
                            <h4 className="font-bold text-sm">{t.layoutDesign}</h4>
                        </div>
                        <EditableText 
                            isTextarea
                            value={page.layoutDesign} 
                            onChange={(val) => handlePageChange(index, 'layoutDesign', val)}
                            className="text-slate-700 text-sm leading-relaxed focus:bg-white/90 min-h-[60px]"
                            placeholder={t.layoutDesignPlaceholder}
                        />
                    </div>
                </div>
            </div>
        ))}

        {/* Add Page Button */}
        <button
            onClick={handleAddPage}
            className="w-full py-4 border-2 border-dashed border-slate-300 rounded-2xl flex items-center justify-center gap-2 text-slate-500 hover:text-violet-600 hover:border-violet-400 hover:bg-violet-50 transition-all font-medium"
        >
            <Plus className="w-5 h-5" />
            {t.addPage}
        </button>
      </div>

      {/* Footer Action */}
      <div className="mt-10 flex justify-center">
        <button 
            onClick={onReset}
            className="text-slate-500 hover:text-violet-600 font-medium flex items-center gap-2 px-6 py-3 rounded-xl hover:bg-white transition-all"
        >
            重新设计一个专案 <ArrowRight className="w-4 h-4" />
        </button>
      </div>

    </div>
  );
};

export default function App() {
  const [step, setStep] = useState('input'); // input, result
  const [isGenerating, setIsGenerating] = useState(false);
  const [language, setLanguage] = useState('zh'); // 'zh' or 'en'
  const [config, setConfig] = useState({
      styleDesc: "",
      pageCount: 5,
      content: "",
      uploadedFile: null,
      includePersona: false,
      targetAudience: "" 
  });
  const [resultData, setResultData] = useState(null);

  // --- API Key State Management with LocalStorage ---
  const [apiKey, setApiKey] = useState(() => {
      // Check localStorage on initial load
      if (typeof window !== 'undefined') {
          return localStorage.getItem('gemini_api_key') || '';
      }
      return '';
  });

  // Save to localStorage whenever apiKey changes
  useEffect(() => {
      if (typeof window !== 'undefined') {
          localStorage.setItem('gemini_api_key', apiKey);
      }
  }, [apiKey]);


  const t = TRANSLATIONS[language];

  const updateConfig = (key, value) => {
      setConfig(prev => ({ ...prev, [key]: value }));
  };

  const handleGenerate = async () => {
    if (!apiKey) {
        alert(language === 'zh' ? "请输入 API Key" : "Please enter API Key");
        return;
    }

    setIsGenerating(true);
    
    try {
        // Pass language and API Key to generator
        const generatedData = await generateWithGemini(config, language, apiKey);
        setResultData(generatedData);
        setStep('result');
        window.scrollTo(0, 0);
    } catch (error) {
        console.error("Failed to generate:", error);
        alert(language === 'zh' 
            ? `生成失败: ${error.message}` 
            : `Generation failed: ${error.message}`);
    } finally {
        setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] font-sans selection:bg-violet-200 selection:text-violet-900">
      <Header language={language} setLanguage={setLanguage} t={t} />
      
      <main>
        {step === 'input' && (
            <InputStep 
                config={config} 
                updateConfig={updateConfig} 
                onGenerate={handleGenerate} 
                isGenerating={isGenerating}
                t={t}
                language={language}
                apiKey={apiKey}
                setApiKey={setApiKey}
            />
        )}
        {step === 'result' && resultData && (
            <ResultStep 
                resultData={resultData} 
                setResultData={setResultData}
                onReset={() => setStep('input')}
                config={config} 
                t={t}
                language={language}
                apiKey={apiKey}
            />
        )}
      </main>

      <footer className="py-8 text-center text-slate-400 text-sm">
        {t.footerText}
      </footer>
    </div>
  );
}
