import React, { useState, useEffect, useRef } from 'react';
import { 
  Layout, 
  FileText, 
  Upload, 
  Sparkles, 
  ImageIcon, 
  Download,
  ArrowRight,
  CheckCircle2,
  Palette,
  MonitorPlay,
  X,
  UserCircle2,
  Check,
  Loader2,
  Users,
  Plus,
  Wand2,
  Trash2,
  Globe,
  ArrowUp,      
  ArrowDown,
  BookOpen,     
  Target,
  LayoutGrid,
  Wand,
  AlignLeft,   
  Columns,     
  LayoutTemplate, 
  ImagePlus,
  Key,          
  Eye,          
  EyeOff,       
  ExternalLink,
  Quote,
  Play,
  HelpCircle,
  Zap,
  Flag,
  Layers
} from 'lucide-react';

// --- Translations ---
const TRANSLATIONS = {
  zh: {
    appTitle: "简报架构生成器",
    apiKeyLabel: "Google Gemini API Key",
    apiKeyPlaceholder: "在此贴上您的 API Key (以 AIza 开头...)",
    apiKeyHelp: "还没有 Key？",
    getKeyLink: "去 Google AI Studio 免费申请",
    apiKeySaved: "API Key 已保存",
    apiKeyRequired: "请先输入 API Key 才能开始生成",
    changeKey: "更换 Key",
    done: "完成",
    selectStyleTitle: "1. 设定简报风格与架构",
    layoutStyleLabel: "排版风格 (Layout Style)",
    layoutTraditional: "传统排版",
    layoutTraditionalDesc: "工整对齐、清晰易读、专业稳重",
    layoutCreative: "创意排版",
    layoutCreativeDesc: "破格重叠、灵活多变、视觉冲击",
    layoutMinimalist: "极简留白",
    layoutMinimalistDesc: "大量留白、呼吸感强、聚焦核心",
    layoutEditorial: "杂志画报",
    layoutEditorialDesc: "图文穿插、大字引言、高级质感",
    layoutComic: "漫画分镜",
    layoutComicDesc: "多格画面、对话气泡、强视觉叙事",
    layoutPictureBook: "绘本排版",
    layoutPictureBookDesc: "满版大图、少字融入、温馨沉浸",
    stylePresetsTitle: "设计风格 (Visual Style)",
    designStyleLabel: "设计风格描述",
    designStylePlaceholder: "请描述您想要的设计风格...",
    structureLabel: "简报叙事架构 (Presentation Structure)",
    structureNarrative: "叙事故事",
    structureNarrativeDesc: "根据上传资料，转化为说故事的方式呈现",
    structureDetailed: "内容详细",
    structureDetailedDesc: "保留完整资讯与数据，制作详尽书面报告",
    structureKeypoint: "重点演示",
    structureKeypointDesc: "精准提取核心重点，适合口头演讲演示",
    presentationElementsLabel: "简报特殊元素 (可多选)",
    elementIntro: "导入 (Hook)",
    elementIntroDesc: "开场提问引发兴趣",
    elementQuestions: "提问 (Question)",
    elementQuestionsDesc: "讲解前后引导思考",
    elementInteraction: "互动 (Interact)",
    elementInteractionDesc: "巩固知识点的小活动",
    elementConclusion: "结语 (Conclusion)",
    elementConclusionDesc: "最后的统整与回顾",
    includePersona: "融合角色设定",
    elementPersonaDesc: "加入专属角色点缀",
    strictExtractionLabel: "严格忠于原文",
    elementStrictDesc: "原汁原味提取原文",
    customPersonaLabel: "自定义 IP 角色 (选填)",
    customPersonaPlaceholder: "描述您的专属角色，例如：一只戴着红帽子的蓝猫...",
    targetAudience: "目标受众 (Target Audience)",
    targetAudiencePlaceholder: "例如：初中学生、潜在投资人、公司高层管理...",
    pageCount: "预计页数",
    contentLabel: "2. 输入内容或上传资料",
    contentPlaceholder: "请贴上您的课文、演讲稿或大纲",
    uploadLabel: "上传参考图片或 PDF (选填)",
    uploadButton: "选择档案 (图片/PDF)",
    uploadHint: "提示：如果是图片，AI 也可提取核心重点并分析视觉风格！",
    generateButton: "开始分析与生成简报",
    generating: "正在呼叫 Gemini API...",
    generatingDesc: "正在根据选择的架构提取原文与重组...",
    resultTitle: "Gemini 生成结果",
    downloadButton: "下载文字档 (.txt)",
    corePoints: "核心重点",
    corePointsPlaceholder: "输入核心重点...",
    visualElements: "视觉元素",
    visualElementsPlaceholder: "输入视觉元素描述...",
    layoutDesign: "排版设计",
    layoutDesignPlaceholder: "输入排版设计指南...",
    addPage: "新增页面 (Add Page)",
    deleteConfirm: "确认删除?",
    pageTitlePlaceholder: "请输入标题 (例如: 市场分析)...",
    aiGenerateButton: "AI 自动生成内容",
    generatingButton: "生成中...",
    enterTitleWarning: "请输入标题!",
    footerText: "@ 2026 Designed by Wei Wen. All rights reserved",
    generatedByGemini: "Generated by Gemini",
    styleSettingApplied: "此设定已由 Gemini 优化并应用于下列所有页面的设计与 AI 生图指令中",
    moveUp: "上移",
    moveDown: "下移",
    personaStyleTitle: "融合角色设定"
  },
  en: {
    appTitle: "Presentation Outline Generator",
    apiKeyLabel: "Google Gemini API Key",
    apiKeyPlaceholder: "Paste your API Key here (starts with AIza...)",
    apiKeyHelp: "Don't have a key?",
    getKeyLink: "Get one free at Google AI Studio",
    apiKeySaved: "API Key Saved",
    apiKeyRequired: "Please enter API Key to start",
    changeKey: "Change Key",
    done: "Done",
    selectStyleTitle: "1. Style & Structure Settings",
    layoutStyleLabel: "Layout Style",
    layoutTraditional: "Traditional",
    layoutTraditionalDesc: "Neat, aligned, highly readable",
    layoutCreative: "Creative",
    layoutCreativeDesc: "Dynamic, overlapping, high impact",
    layoutMinimalist: "Minimalist",
    layoutMinimalistDesc: "Lots of whitespace, focus on core",
    layoutEditorial: "Editorial",
    layoutEditorialDesc: "Text & image interplay, bold quotes",
    layoutComic: "Comic Panels",
    layoutComicDesc: "Grid panels, speech bubbles, sequential",
    layoutPictureBook: "Picture Book",
    layoutPictureBookDesc: "Large imagery, minimal text, immersive",
    stylePresetsTitle: "Visual Style",
    designStyleLabel: "Style Description",
    designStylePlaceholder: "Describe your desired style...",
    structureLabel: "Presentation Structure",
    structureNarrative: "Narrative Story",
    structureNarrativeDesc: "Transform uploaded data into a storytelling format",
    structureDetailed: "Detailed Content",
    structureDetailedDesc: "Retain full info & data for a comprehensive report",
    structureKeypoint: "Key Points",
    structureKeypointDesc: "Extract core highlights for speeches & pitches",
    presentationElementsLabel: "Special Elements (Multi-select)",
    elementIntro: "Intro (Hook)",
    elementIntroDesc: "Opening question to engage",
    elementQuestions: "Questions",
    elementQuestionsDesc: "Provoke thought during content",
    elementInteraction: "Interaction",
    elementInteractionDesc: "Activities to consolidate knowledge",
    elementConclusion: "Conclusion",
    elementConclusionDesc: "Final summary and review",
    includePersona: "Include Persona",
    elementPersonaDesc: "Consistent IP character",
    strictExtractionLabel: "Strict Fidelity",
    elementStrictDesc: "Exact quotes, no rewrites",
    customPersonaLabel: "Custom IP Character (Optional)",
    customPersonaPlaceholder: "Describe your character, e.g., A blue cat wearing a red hat...",
    targetAudience: "Target Audience",
    targetAudiencePlaceholder: "E.g., Junior students, Potential Investors, C-Level Execs...",
    pageCount: "Estimated Pages",
    contentLabel: "2. Content Source",
    contentPlaceholder: "Paste your text, speech, or outline here",
    uploadLabel: "Upload Reference Image or PDF (Optional)",
    uploadButton: "Choose File (Image/PDF)",
    uploadHint: "Tip: AI can extract core points from images and analyze visual style!",
    generateButton: "Analyze & Generate Presentation",
    generating: "Calling Gemini API...",
    generatingDesc: "Strictly extracting content based on selected mode...",
    resultTitle: "Gemini Result",
    downloadButton: "Download Text (.txt)",
    corePoints: "Core Points",
    corePointsPlaceholder: "Enter core points...",
    visualElements: "Visual Elements",
    visualElementsPlaceholder: "Enter visual element description...",
    layoutDesign: "Layout Design",
    layoutDesignPlaceholder: "Enter layout instructions...",
    addPage: "Add Page",
    deleteConfirm: "Confirm Delete?",
    pageTitlePlaceholder: "Enter title (e.g., Market Analysis)...",
    aiGenerateButton: "AI Generate Content",
    generatingButton: "Generating...",
    enterTitleWarning: "Enter Title!",
    footerText: "@ 2026 Designed by Wei Wen. All rights reserved",
    generatedByGemini: "Generated by Gemini",
    styleSettingApplied: "This setting has been optimized by Gemini and applied to all pages below.",
    moveUp: "Move Up",
    moveDown: "Move Down",
    personaStyleTitle: "Persona Integration Setting"
  }
};

// --- Style Presets ---
const GET_STYLE_PRESETS = (lang) => {
  const presets = [
    { id: 1, label: lang === 'zh' ? "吉卜力自然风" : "Ghibli Natural", value: lang === 'zh' ? "吉卜力动画风格，高饱和度的蓝天白云，茂密的绿色植被，手绘水彩质感。" : "Ghibli animation style, high saturation blue sky, lush green vegetation, hand-painted watercolor texture." },
    { id: 2, label: lang === 'zh' ? "游戏任务地图" : "Game Quest Map", value: lang === 'zh' ? "ISO 2.5D 视角，游戏 UI 界面元素，任务节点路径，像素或矢量风格。" : "ISO 2.5D perspective, game UI elements, quest path, pixel or vector style." },
    { id: 3, label: lang === 'zh' ? "漫画风格" : "Comic/Manga", value: lang === 'zh' ? "高对比度波普色彩，使用对话气泡、速度线、粗体大字强调关键词。" : "High contrast pop colors, using speech bubbles, speed lines, bold characters to emphasize keywords." },
    { id: 4, label: lang === 'zh' ? "水彩风格" : "Watercolor", value: lang === 'zh' ? "柔和的水痕晕染，透明感，艺术气息，优雅的手绘外观。" : "Soft water stains, transparency, artistic atmosphere, elegant hand-painted look." },
    { id: 5, label: lang === 'zh' ? "粉彩柔和" : "Pastel Soft", value: lang === 'zh' ? "低饱和度马卡龙色系，梦幻、轻盈、柔和的视觉感受。" : "Low saturation macaron colors, dreamy, light, and soft visual experience." },
    { id: 6, label: lang === 'zh' ? "手绘插画" : "Hand-drawn", value: lang === 'zh' ? "温暖亲切，手绘风格图标和边框，自然不拘束的线条。" : "Warm and friendly, hand-drawn icons and borders, natural lines." },
    { id: 7, label: lang === 'zh' ? "温暖疗愈" : "Warm & Healing", value: lang === 'zh' ? "大地色系，柔和的圆角，自然纹理，营造放松信任的氛围。" : "Earth tones, soft rounded corners, natural textures, trusting atmosphere." },
    { id: 8, label: lang === 'zh' ? "日系漫画" : "Japanese Manga", value: lang === 'zh' ? "经典日系漫画风格，黑白网点，丰富情感表达，连续的分镜排版。" : "Classic manga style, monochrome screentones, expressive emotions, sequential panel layout." },
    { id: 9, label: lang === 'zh' ? "复古怀旧" : "Retro Nostalgic", value: lang === 'zh' ? "低保真质感，80/90年代配色，复古衬线字体，胶片滤镜效果。" : "Lo-fi texture, 80s/90s color scheme, retro serif fonts, film filter effects." },
    { id: 10, label: lang === 'zh' ? "活泼童趣" : "Playful & Childlike", value: lang === 'zh' ? "高饱和三原色，简单的几何图形，充满活力的涂鸦风格。" : "High saturation primary colors, simple geometric shapes, doodle style." },
    { id: 11, label: lang === 'zh' ? "自然有机" : "Natural Organic", value: lang === 'zh' ? "再生纸纹理，植物元素，绿色和土色调，环保自然感。" : "Recycled paper texture, plant elements, green and earthy tones, eco-friendly feel." },
    { id: 12, label: lang === 'zh' ? "赛博庞克" : "Cyberpunk", value: lang === 'zh' ? "霓虹对比色，深色背景，故障艺术，未来科技美学。" : "Neon contrast colors, dark background, Glitch Art, futuristic aesthetics." },
    { id: 13, label: lang === 'zh' ? "扁平化设计" : "Flat Design", value: lang === 'zh' ? "无阴影，纯色色块，矢量图标，现代简洁的 UI 风格。" : "No shadows, solid color blocks, vector icons, modern UI style." },
    { id: 14, label: lang === 'zh' ? "绘本治愈" : "Picture Book Therapy", value: lang === 'zh' ? "柔和色调，隐喻意象，专注于情感表达和故事性。" : "Soft tones, metaphorical imagery, focusing on emotional storytelling." },
    { id: 15, label: lang === 'zh' ? "麦肯锡风格" : "McKinsey Corporate", value: lang === 'zh' ? "高度专业，海军蓝和高级灰，严格对齐，数据驱动的层级结构。" : "Highly professional, navy blue and grey, strict alignment, data-driven hierarchy." },
    { id: 16, label: lang === 'zh' ? "Google四原色" : "Google 4-Color", value: lang === 'zh' ? "干净的白色背景，搭配蓝、红、黄、绿的几何图形，现代科技感。" : "Clean white background with blue, red, yellow, green geometric shapes." },
    { id: 17, label: lang === 'zh' ? "玻璃拟态" : "Glassmorphism", value: lang === 'zh' ? "半透明毛玻璃效果，鲜艳渐变背景，细腻光泽边框，悬浮元素。" : "Frosted glass effects, vibrant gradients, subtle borders, floating elements." },
    { id: 18, label: lang === 'zh' ? "液态玻璃" : "Liquid Glass", value: lang === 'zh' ? "流动的 3D 形态，光泽折射材质，动态全息渐变。" : "Fluid 3D shapes, glossy refractive materials, dynamic holographic gradients." },
    { id: 19, label: lang === 'zh' ? "可爱萌系" : "Cute & Moe", value: lang === 'zh' ? "圆润的 UI 元素，柔和糖果色，胖乎乎的吉祥物，活泼的字体。" : "Round UI elements, soft candy colors, chubby mascots, bubbly fonts." },
    { id: 20, label: lang === 'zh' ? "北欧风" : "Nordic Minimalist", value: lang === 'zh' ? "中性色调，柔和大地色，木材和亚麻等原始纹理，极简美学。" : "Neutral tones, muted earth colors, raw textures like wood and linen, minimalist aesthetic." }
  ];
  return presets;
};

// --- Options Helpers ---
const GET_STRUCTURE_OPTIONS = (lang, t) => [
    { id: 'story', label: t.structureNarrative, desc: t.structureNarrativeDesc, icon: <BookOpen className="w-5 h-5" />, color: "bg-amber-100 text-amber-700 border-amber-200" },
    { id: 'detail', label: t.structureDetailed, desc: t.structureDetailedDesc, icon: <FileText className="w-5 h-5" />, color: "bg-blue-100 text-blue-700 border-blue-200" },
    { id: 'keypoint', label: t.structureKeypoint, desc: t.structureKeypointDesc, icon: <Target className="w-5 h-5" />, color: "bg-rose-100 text-rose-700 border-rose-200" }
];

const GET_LAYOUT_OPTIONS = (lang, t) => [
    { id: 'traditional', label: t.layoutTraditional, desc: t.layoutTraditionalDesc, icon: <LayoutGrid className="w-5 h-5" />, color: "bg-blue-100 text-blue-700 border-blue-200" },
    { id: 'creative', label: t.layoutCreative, desc: t.layoutCreativeDesc, icon: <Wand className="w-5 h-5" />, color: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200" },
    { id: 'minimalist', label: t.layoutMinimalist, desc: t.layoutMinimalistDesc, icon: <AlignLeft className="w-5 h-5" />, color: "bg-emerald-100 text-emerald-700 border-emerald-200" },
    { id: 'editorial', label: t.layoutEditorial, desc: t.layoutEditorialDesc, icon: <Columns className="w-5 h-5" />, color: "bg-orange-100 text-orange-700 border-orange-200" },
    { id: 'comic', label: t.layoutComic, desc: t.layoutComicDesc, icon: <LayoutTemplate className="w-5 h-5" />, color: "bg-purple-100 text-purple-700 border-purple-200" },
    { id: 'pictureBook', label: t.layoutPictureBook, desc: t.layoutPictureBookDesc, icon: <ImagePlus className="w-5 h-5" />, color: "bg-pink-100 text-pink-700 border-pink-200" }
];

// --- Helpers ---
const fileToBase64 = (file) => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result.split(',')[1]);
    reader.onerror = error => reject(error);
  });
};

const normalizeContent = (content) => {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.map(item => String(item)).join('\n');
  if (typeof content === 'object' && content !== null) return JSON.stringify(content);
  if (content === undefined || content === null) return "";
  return String(content);
};

const getLayoutInstruction = (layoutStyle) => {
    switch (layoutStyle) {
        case 'creative': return "LAYOUT: Use creative, dynamic, asymmetrical layouts. Break the grid.";
        case 'minimalist': return "LAYOUT: Extreme minimalist Zen style. Large whitespace, central focal points.";
        case 'editorial': return "LAYOUT: Magazine style. Bold quotes, multi-column grid, strong typography.";
        case 'comic': return "LAYOUT: Comic panels. Divide slide into multiple dynamic blocks with speech bubbles.";
        case 'pictureBook': return "LAYOUT: Full-bleed imagery. Text integrated into illustrations elegantly.";
        case 'traditional':
        default: return "LAYOUT: Traditional, clean, and well-organized layouts. Professional and aligned.";
    }
};

// --- API Logic ---
const generateWithGemini = async (config, language, apiKey) => {
  const { styleDesc, pageCount, content, uploadedFile, includePersona, targetAudience, structureType, layoutStyle, customPersona, strictExtraction, addIntro, addQuestions, addInteraction, addConclusion } = config;

  if (!apiKey) throw new Error("API Key Missing");

  const langInstruction = language === 'en' ? 'English' : 'Simplified Chinese (简体中文)';
  const layoutInstruction = getLayoutInstruction(layoutStyle);

  let structureInstruction = "";
  switch (structureType) {
      case 'story':
          structureInstruction = "STRUCTURE: NARRATIVE STORY. Reorganize the exact source content into a chronological/storytelling flow (Background -> Conflict -> Resolution).";
          break;
      case 'detail':
          structureInstruction = "STRUCTURE: DETAILED CONTENT. Preserve almost all facts, data, and details from the source. Create a highly comprehensive report layout.";
          break;
      case 'keypoint':
          structureInstruction = "STRUCTURE: KEY POINTS. Extract only the most crucial highlights. Use extreme minimalism for text.";
          break;
      default:
          structureInstruction = "STRUCTURE: Standard Presentation.";
  }

  let personaPrompt = "DISABLED.";
  if (includePersona) {
      if (customPersona && customPersona.trim() !== "") {
           personaPrompt = `ENABLED. You MUST use the user's specific custom character: "${customPersona}". It MUST NOT be the main focus. The Global Style description MUST end with: '页面角落加入专属角色（${customPersona}）作为点缀与搭衬，不喧宾夺主。角色保持一致，贯穿始终。依内容语意仅微调其动作或小道具。' In 'visualElements' for each page, briefly describe this EXACT SAME character's subtle pose or prop.`;
      } else {
           personaPrompt = `ENABLED. Invent ONE specific, consistent character. The Global Style description MUST end with: '根据简报内容量身定制了一个专属角色（并在括号内注明具体形象，例如：一只戴单片眼镜的侦探狗）。在页面角落加入此小尺寸角色作为点缀与搭衬，不喧宾夺主。角色保持一致，贯穿始终。依内容语意仅微调其动作或小道具。' In 'visualElements' for each page, briefly describe this EXACT SAME character's subtle pose or prop.`;
      }
  }

  let contentRule = strictExtraction 
      ? `CRITICAL CONTENT RULE (STRICT TEXT FIDELITY):
- You are an EXTRACTOR, not a copywriter. 
- You MUST use the EXACT wording, vocabulary, and sentences from the provided Source Content. 
- DO NOT paraphrase. DO NOT substitute words with synonyms. DO NOT alter the original meaning. 
- If the user provides a textbook text, strictly quote the textbook's sentences to form the points.`
      : `CONTENT FORMATTING RULE:
- Summarize, refine, and optimize the source content into impactful bullet points suitable for a presentation. 
- You are encouraged to paraphrase and improve the wording for better flow and visual impact, as long as the core meaning is preserved.`;

  // --- Presentation Elements Logic ---
  let elementsInstructions = [];
  if (addIntro) elementsInstructions.push("- INCLUSION: The FIRST page MUST be an 'Intro/Hook (导入)', starting with a thought-provoking question to engage the audience based on the content.");
  if (addQuestions) elementsInstructions.push("- INCLUSION: Integrate 'Thought-Provoking Questions (提问)' within the content pages to stimulate thinking before or after explaining concepts.");
  if (addInteraction) elementsInstructions.push("- INCLUSION: Include 'Interactive Elements (互动)' to consolidate knowledge points (e.g., quick quiz, discussion prompt, reflection task).");
  if (addConclusion) elementsInstructions.push("- INCLUSION: The FINAL page MUST be a 'Conclusion (结语)', providing a clear summary and review of the entire topic.");

  let elementsPrompt = elementsInstructions.length > 0 
      ? `\n    PRESENTATION ELEMENTS REQUESTED (MANDATORY):\n    ${elementsInstructions.join('\n    ')}\n    *Note: Even if STRICT TEXT FIDELITY is enabled, formulate these interactions/questions STRICTLY around the exact concepts found in the source text.*` 
      : "";

  const systemPrompt = `
    You are a professional Presentation Designer and AI Art Director.
    Your task is to deeply analyze the user's source content and transform it into a structured presentation outline.

    CORE ANALYTICAL FRAMEWORK (You MUST filter the content through these 4 pillars):
    1. TARGET AUDIENCE: "${targetAudience || "General Audience"}". The depth, tone, and visual appeal MUST be specifically tailored for them.
    2. DESIGN STYLE: "${styleDesc}". You MUST translate this requested style into a cohesive 'globalStyle' and apply it conceptually to every 'visualElements'.
    3. STRUCTURE MODE: ${structureType} (${structureInstruction}). The way you extract, logically group, and present the Source Content MUST strictly follow this narrative or data structure.
    4. LAYOUT RULE: ${layoutStyle} (${layoutInstruction}). Every page's 'layoutDesign' must be dictated by this specific layout system.
    ${elementsPrompt}

    Output MUST be valid JSON with this structure:
    {
      "topic": "Creative Main Title based on source",
      "globalStyle": {
        "title": "Style Name",
        "content": "Detailed description of colors, fonts, and mood."
      },
      "pages": [
        {
          "page": 1,
          "title": "Page Title",
          "corePoints": "Extracted key points based on Structure Mode. If this page serves an Intro/Question/Interaction/Conclusion purpose, format it appropriately.",
          "visualElements": "Description of visual elements in ${langInstruction}.",
          "layoutDesign": "Specific layout instructions following the Layout Rule"
        }
      ]
    }

    ${contentRule}

    ADDITIONAL CONSTRAINTS:
    - Generate exactly ${pageCount} pages.
    - Language: ALL JSON values must be in ${langInstruction}.
    - Persona Mode: ${personaPrompt}
    - Content Source: Use this context: "${content}". 
    ${uploadedFile ? "- FILE UPLOADED: Use the attached file as the STRICT PRIMARY SOURCE." : ""}
  `;

  let contents = [];
  
  if (uploadedFile) {
    const fileBase64 = await fileToBase64(uploadedFile);
    const isImage = uploadedFile.type.startsWith('image/');
    const fileInstruction = isImage 
        ? "CRITICAL TASK: Read and extract all visible text from this image exactly as written. Then analyze its visual style to inform 'globalStyle'."
        : "CRITICAL TASK: Read the attached document. Extract the exact sentences and data to structure the presentation. DO NOT rephrase.";

    contents = [{
      parts: [
        { text: systemPrompt },
        { text: fileInstruction },
        { inlineData: { mimeType: uploadedFile.type, data: fileBase64 } }
      ]
    }];
  } else {
    contents = [{ parts: [{ text: systemPrompt }] }];
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: contents,
          generationConfig: { responseMimeType: "application/json" }
        })
      }
    );

    if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error?.message || 'API Request Failed');
    }
    const data = await response.json();
    const generatedText = data.candidates[0].content.parts[0].text;
    const parsedData = JSON.parse(generatedText);

    if (parsedData.globalStyle) {
        parsedData.globalStyle.content = normalizeContent(parsedData.globalStyle.content);
    }
    if (Array.isArray(parsedData.pages)) {
        parsedData.pages = parsedData.pages.map(page => ({
            ...page,
            title: normalizeContent(page.title),
            corePoints: normalizeContent(page.corePoints),
            visualElements: normalizeContent(page.visualElements),
            layoutDesign: normalizeContent(page.layoutDesign)
        }));
    }

    return parsedData;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

const generatePageContent = async (config, pageTitle, pageCorePoints, currentTopic, globalStyle, language, apiKey) => {
  const { styleDesc, targetAudience, includePersona, content, uploadedFile, structureType, layoutStyle, customPersona, strictExtraction } = config;
  
  if (!apiKey) throw new Error("API Key Missing");

  const langInstruction = language === 'en' ? 'English' : 'Simplified Chinese (简体中文)';
  const layoutInstruction = getLayoutInstruction(layoutStyle);

  let structureInstruction = "";
  if (structureType === 'story') structureInstruction = "Structure as a narrative flow.";
  else if (structureType === 'detail') structureInstruction = "Provide comprehensive details.";
  else structureInstruction = "Provide minimal core highlights.";

  let personaPrompt = "DISABLED.";
  if (includePersona) {
      personaPrompt = `ENABLED. The slide features a character. ${customPersona ? `Custom character: "${customPersona}".` : `Use the exact same character defined in Global Style.`} Rule: 角色保持一致，贯穿始终 (Character must be strictly consistent and appear throughout). Describe its subtle pose/props without dominating the visual.`;
  }

  let contentRule = strictExtraction
      ? `CRITICAL CONTENT RULE (STRICT TEXT FIDELITY):
- Do NOT act as a copywriter. Act as an extractor and formatter.
- If 'User provided specific text' exists: Treat it as an absolute baseline. Do NOT rewrite it or use synonyms. Only format it (e.g., into bullets) to match the Structure Mode.
- If empty: Extract exact quotes/sentences from the Global Content that relate to the Slide Title. Do NOT paraphrase.`
      : `CONTENT FORMATTING RULE:
- Act as a copywriter and presentation expert.
- If 'User provided specific text' exists: Refine and optimize it for a presentation slide. Make it punchy and impactful.
- If empty: Summarize relevant points from the Global Content. Paraphrase for better presentation flow.`;

  const userPointsContext = pageCorePoints && pageCorePoints.trim() !== "" 
    ? `User provided specific text for this slide: "${pageCorePoints}".`
    : "User has not provided specific points for this slide, extract exactly from Source Material.";

  const systemPrompt = `
    You are a professional Presentation Designer.
    Refine slide "${pageTitle}" for topic "${currentTopic}".
    
    CORE ANALYTICAL FRAMEWORK (Strictly apply to this slide):
    1. Target Audience: "${targetAudience || "General Audience"}" (Adjust text tone to fit them perfectly).
    2. Global Style & User Preference: "${globalStyle.title}" (${globalStyle.content}) + "${styleDesc}".
    3. Layout Rule: ${layoutInstruction} (Dictates the 'layoutDesign').
    4. Structure Mode: ${structureType} (${structureInstruction}) (Dictates how much detail goes into 'corePoints').
    
    CONTEXT & RULES:
    - Persona Mode: ${personaPrompt}
    - User Provided Global Content/Context: "${content}"
    - Slide Specific Input: ${userPointsContext}

    ${contentRule}

    Output MUST be valid JSON with this structure:
    {
      "corePoints": "Extracted text/quotes based on Structure Mode.",
      "visualElements": "Description of visuals in ${langInstruction}.",
      "layoutDesign": "Layout instructions strictly matching the layout rule."
    }

    CONSTRAINTS:
    1. Language: ${langInstruction}.
  `;

  let contents = [];
  
  if (uploadedFile) {
    const fileBase64 = await fileToBase64(uploadedFile);
    const isImage = uploadedFile.type.startsWith('image/');
    const fileInstruction = isImage 
        ? "IMAGE CONTEXT: Extract text exactly as seen in the image."
        : "DOCUMENT CONTEXT: Extract text exactly as written in the document.";

    contents = [{
      parts: [
        { text: systemPrompt },
        { text: fileInstruction },
        { inlineData: { mimeType: uploadedFile.type, data: fileBase64 } }
      ]
    }];
  } else {
    contents = [{ parts: [{ text: systemPrompt }] }];
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: contents,
          generationConfig: { responseMimeType: "application/json" }
        })
      }
    );

    if (!response.ok) throw new Error('API Request Failed');
    const data = await response.json();
    const parsedData = JSON.parse(data.candidates[0].content.parts[0].text);

    return {
        corePoints: normalizeContent(parsedData.corePoints),
        visualElements: normalizeContent(parsedData.visualElements),
        layoutDesign: normalizeContent(parsedData.layoutDesign)
    };

  } catch (error) {
    console.error("Gemini Page Gen Error:", error);
    throw error;
  }
};

// --- UI Components ---
const ApiKeyInput = ({ apiKey, setApiKey, t }) => {
    const [showKey, setShowKey] = useState(false);
    const [isEditing, setIsEditing] = useState(!apiKey);

    useEffect(() => {
        if (!apiKey) setIsEditing(true);
    }, [apiKey]);
    
    if (!isEditing && apiKey) {
        return (
            <div className="bg-violet-50 border border-violet-100 rounded-2xl p-4 mb-8 flex items-center justify-between animate-fade-in relative overflow-hidden shadow-sm">
                 <div className="absolute top-0 right-0 w-32 h-32 bg-violet-200 rounded-full blur-3xl opacity-30 -mr-10 -mt-10"></div>
                 <div className="flex items-center gap-3 relative z-10">
                    <div className="w-10 h-10 bg-green-100 rounded-xl flex items-center justify-center border border-green-200">
                        <CheckCircle2 className="w-5 h-5 text-green-600" />
                    </div>
                    <div>
                        <div className="text-xs font-bold text-violet-900 uppercase tracking-wider">{t.apiKeyLabel}</div>
                        <div className="text-sm text-green-600 font-bold flex items-center gap-1.5 mt-0.5">
                            <CheckCircle2 className="w-4 h-4" />
                            <span>{t.apiKeySaved}</span>
                        </div>
                    </div>
                </div>
                <button 
                    onClick={() => setIsEditing(true)}
                    className="relative z-10 text-sm font-medium text-slate-500 hover:text-violet-600 bg-white hover:bg-violet-50 border border-slate-200 hover:border-violet-200 px-4 py-2 rounded-lg transition-all"
                >
                    {t.changeKey}
                </button>
            </div>
        );
    }

    return (
        <div className="bg-violet-50 border border-violet-100 rounded-2xl p-6 mb-8 relative overflow-hidden animate-fade-in">
            <div className="absolute top-0 right-0 w-32 h-32 bg-violet-200 rounded-full blur-3xl opacity-30 -mr-10 -mt-10"></div>
            
            <div className="relative z-10">
                <div className="flex items-center justify-between mb-4">
                    <label className="flex items-center gap-2 text-sm font-bold text-violet-900">
                        <Key className="w-4 h-4 text-violet-600" />
                        {t.apiKeyLabel}
                    </label>
                    <a 
                        href="https://aistudio.google.com/app/apikey" 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="text-xs font-medium text-violet-600 hover:text-violet-800 flex items-center gap-1 hover:underline"
                    >
                        {t.apiKeyHelp} {t.getKeyLink}
                        <ExternalLink className="w-3 h-3" />
                    </a>
                </div>
                
                <div className="relative">
                    <input
                        type={showKey ? "text" : "password"}
                        value={apiKey}
                        onChange={(e) => setApiKey(e.target.value)}
                        placeholder={t.apiKeyPlaceholder}
                        className="w-full pl-4 pr-24 py-3 bg-white border border-violet-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-transparent outline-none transition-all shadow-sm font-mono text-sm"
                    />
                    <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
                        <button
                            onClick={() => setShowKey(!showKey)}
                            className="p-2 text-slate-400 hover:text-violet-600 hover:bg-violet-50 rounded-lg transition-colors"
                            type="button"
                        >
                            {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                        </button>
                    </div>
                </div>
                
                {apiKey && apiKey.startsWith("AIza") && (
                     <div className="mt-4 flex items-center justify-between animate-fade-in">
                         <div className="flex items-center gap-1.5 text-xs text-green-600 font-medium">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            {t.apiKeySaved}
                         </div>
                         <button
                            onClick={() => setIsEditing(false)}
                            className="flex items-center gap-2 bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold px-4 py-2 rounded-lg transition-colors shadow-sm"
                         >
                            <Check className="w-3 h-3" />
                            {t.done}
                         </button>
                     </div>
                )}
            </div>
        </div>
    );
};

const Header = ({ language, setLanguage, t }) => (
  <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-violet-600 rounded-xl flex items-center justify-center shadow-lg shadow-violet-200">
          <MonitorPlay className="text-white w-6 h-6" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight hidden md:block">{t.appTitle}</h1>
          <h1 className="text-lg font-bold text-slate-900 tracking-tight md:hidden">Gemini Slides</h1>
          <div className="flex items-center gap-1">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
            </span>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">Powered by Gemini ✨</span>
          </div>
        </div>
      </div>
      
      <button 
        onClick={() => setLanguage(prev => prev === 'zh' ? 'en' : 'zh')}
        className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-slate-100 transition-colors border border-transparent hover:border-slate-200"
      >
        <Globe className="w-4 h-4 text-slate-500" />
        <span className="text-sm font-medium text-slate-700">
            {language === 'zh' ? 'English' : '中文'}
        </span>
      </button>
    </div>
  </header>
);

const InputStep = ({ config, updateConfig, onGenerate, isGenerating, t, language, apiKey, setApiKey }) => {
  const fileInputRef = useRef(null);
  const stylePresets = GET_STYLE_PRESETS(language);
  const structureOptions = GET_STRUCTURE_OPTIONS(language, t);
  const layoutOptions = GET_LAYOUT_OPTIONS(language, t);

  // 简报特殊元素与约束选项定义
  const presentationElements = [
    { id: 'addIntro', label: t.elementIntro, desc: t.elementIntroDesc, icon: <Play className="w-4 h-4" />, color: "border-sky-500 bg-sky-50 text-sky-700 ring-sky-500" },
    { id: 'addQuestions', label: t.elementQuestions, desc: t.elementQuestionsDesc, icon: <HelpCircle className="w-4 h-4" />, color: "border-indigo-500 bg-indigo-50 text-indigo-700 ring-indigo-500" },
    { id: 'addInteraction', label: t.elementInteraction, desc: t.elementInteractionDesc, icon: <Zap className="w-4 h-4" />, color: "border-amber-500 bg-amber-50 text-amber-700 ring-amber-500" },
    { id: 'addConclusion', label: t.elementConclusion, desc: t.elementConclusionDesc, icon: <Flag className="w-4 h-4" />, color: "border-emerald-500 bg-emerald-50 text-emerald-700 ring-emerald-500" },
    { id: 'includePersona', label: t.includePersona, desc: t.elementPersonaDesc, icon: <UserCircle2 className="w-4 h-4" />, color: "border-violet-500 bg-violet-50 text-violet-700 ring-violet-500" },
    { id: 'strictExtraction', label: t.strictExtractionLabel, desc: t.elementStrictDesc, icon: <Quote className="w-4 h-4" />, color: "border-rose-500 bg-rose-50 text-rose-700 ring-rose-500" }
  ];

  const handleFileClick = () => {
    fileInputRef.current.click();
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      updateConfig('uploadedFile', file);
    }
  };

  const clearFile = (e) => {
      e.stopPropagation();
      updateConfig('uploadedFile', null);
      if (fileInputRef.current) {
          fileInputRef.current.value = "";
      }
  };

  const isButtonDisabled = isGenerating || !apiKey || apiKey.length < 10;

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 animate-fade-in">
      
      <ApiKeyInput apiKey={apiKey} setApiKey={setApiKey} t={t} />

      <div className="bg-white rounded-3xl shadow-xl shadow-slate-200/50 p-8 border border-white relative overflow-hidden">
        {isGenerating && (
            <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center">
                 <Loader2 className="w-12 h-12 text-violet-600 animate-spin mb-4" />
                 <h3 className="text-xl font-bold text-slate-800">✨ Gemini {language === 'zh' ? '正在提取内容...' : 'Extracting content...'}</h3>
                 <p className="text-slate-500">{t.generatingDesc}</p>
            </div>
        )}

        <div className="mb-8 pb-6 border-b border-slate-100 flex items-center gap-3">
          <div className="w-10 h-10 bg-violet-100 rounded-xl flex items-center justify-center text-violet-600 shrink-0">
             <FileText className="w-6 h-6" />
          </div>
          <h2 className="text-xl font-bold text-slate-800">{t.selectStyleTitle}</h2>
        </div>

        <div className="space-y-8">
            {/* Layout Type Selection */}
            <div>
                 <label className="block text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <LayoutGrid className="w-4 h-4 text-violet-500" />
                    {t.layoutStyleLabel}
                 </label>
                 <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                    {layoutOptions.map((option) => (
                        <button
                            key={option.id}
                            onClick={() => updateConfig('layoutStyle', option.id)}
                            className={`flex flex-col items-start p-3 rounded-xl border transition-all ${
                                config.layoutStyle === option.id
                                ? `${option.color.replace('text-', 'border-').replace('bg-', 'bg-opacity-20 ')} shadow-md ring-1 ring-offset-1 ring-transparent ring-violet-500`
                                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                            }`}
                        >
                            <div className={`p-2 rounded-lg flex-shrink-0 mb-2 ${config.layoutStyle === option.id ? 'bg-white shadow-sm' : 'bg-slate-100'}`}>
                                {option.icon}
                            </div>
                            <div className="text-left">
                                <h3 className={`text-sm font-bold mb-1 ${config.layoutStyle === option.id ? 'text-slate-900' : 'text-slate-700'}`}>
                                    {option.label}
                                </h3>
                                <p className="text-xs text-slate-500 leading-relaxed line-clamp-2">
                                    {option.desc}
                                </p>
                            </div>
                        </button>
                    ))}
                 </div>
            </div>

            {/* Structure Type Selection */}
            <div>
                <label className="block text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <Layout className="w-4 h-4 text-violet-500" />
                    {t.structureLabel}
                </label>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {structureOptions.map((option) => (
                        <button
                            key={option.id}
                            onClick={() => updateConfig('structureType', option.id)}
                            className={`flex flex-col items-start p-4 rounded-xl border transition-all ${
                                config.structureType === option.id
                                ? `${option.color.replace('text-', 'border-').replace('bg-', 'bg-opacity-20 ')} shadow-md ring-1 ring-offset-1 ring-transparent`
                                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                            } ${config.structureType === option.id ? 'ring-violet-500' : ''}`}
                        >
                            <div className={`p-2 rounded-lg mb-3 ${config.structureType === option.id ? 'bg-white shadow-sm' : 'bg-slate-100'}`}>
                                {option.icon}
                            </div>
                            <h3 className={`text-sm font-bold mb-1 ${config.structureType === option.id ? 'text-slate-900' : 'text-slate-700'}`}>
                                {option.label}
                            </h3>
                            <p className="text-xs text-slate-500 text-left leading-relaxed">
                                {option.desc}
                            </p>
                        </button>
                    ))}
                </div>
            </div>

            {/* Style Presets */}
            <div>
                 <label className="block text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-violet-500" />
                    {t.stylePresetsTitle}
                 </label>
                 <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                    {stylePresets.map((style) => (
                        <button
                        key={style.id}
                        onClick={() => updateConfig('styleDesc', style.value)}
                        className={`text-left p-3 border rounded-xl transition-all group h-full flex flex-col justify-between ${
                            config.styleDesc === style.value 
                            ? 'bg-violet-50 border-violet-500 shadow-sm ring-1 ring-violet-500' 
                            : 'bg-slate-50 border-slate-200 hover:border-violet-300 hover:bg-violet-50'
                        }`}
                        >
                        <span className={`text-xs font-bold ${config.styleDesc === style.value ? 'text-violet-700' : 'text-slate-700 group-hover:text-violet-700'}`}>
                            {style.label}
                        </span>
                        </button>
                    ))}
                 </div>
            </div>

            {/* Design Style Description */}
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">{t.designStyleLabel}</label>
              <textarea
                value={config.styleDesc}
                onChange={(e) => updateConfig('styleDesc', e.target.value)}
                placeholder={t.designStylePlaceholder}
                className="w-full h-24 p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-violet-500 focus:bg-white transition-all resize-none shadow-inner"
              />
            </div>

            {/* 简报特殊元素与约束 (多选) */}
            <div>
                <label className="block text-sm font-semibold text-slate-700 mb-3 flex items-center gap-2">
                    <Layers className="w-4 h-4 text-violet-500" />
                    {t.presentationElementsLabel}
                </label>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                    {presentationElements.map((element) => {
                        const isSelected = config[element.id];
                        return (
                            <button
                                key={element.id}
                                onClick={() => updateConfig(element.id, !isSelected)}
                                className={`flex flex-col items-start p-3 rounded-xl border transition-all text-left ${
                                    isSelected
                                    ? element.color + " shadow-sm ring-1 ring-offset-1 ring-transparent"
                                    : "bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50"
                                }`}
                            >
                                <div className="flex items-center gap-2 mb-1 w-full">
                                    {/* 独立的打勾方块 */}
                                    <div className={`w-4 h-4 rounded-sm border flex items-center justify-center transition-colors flex-shrink-0 ${
                                        isSelected ? 'bg-white border-slate-400 text-slate-700' : 'border-slate-300 text-transparent bg-white'
                                    }`}>
                                        <Check className="w-3 h-3 stroke-[4]" />
                                    </div>
                                    {/* 图标与标题 */}
                                    <div className={`flex items-center gap-1.5 ${isSelected ? 'text-current' : 'text-slate-700'}`}>
                                        <span className={isSelected ? 'opacity-80' : 'text-slate-400'}>{element.icon}</span>
                                        <h3 className="text-sm font-bold">
                                            {element.label}
                                        </h3>
                                    </div>
                                </div>
                                {/* 描述文字，左侧留出对齐空间 */}
                                <p className={`text-[10px] leading-relaxed mt-1 pl-6 ${isSelected ? 'text-current opacity-80' : 'text-slate-500'}`}>
                                    {element.desc}
                                </p>
                            </button>
                        );
                    })}
                </div>

                {/* 动态显示的自定义角色输入框 */}
                {config.includePersona && (
                    <div className="mt-4 p-4 bg-violet-50/50 border border-violet-100 rounded-xl animate-fade-in-up">
                        <label className="block text-xs font-semibold text-slate-600 mb-2 flex items-center gap-2">
                            <UserCircle2 className="w-4 h-4 text-violet-500" />
                            {t.customPersonaLabel}
                        </label>
                        <input 
                            type="text" 
                            value={config.customPersona || ''}
                            onChange={(e) => updateConfig('customPersona', e.target.value)}
                            placeholder={t.customPersonaPlaceholder}
                            className="w-full p-3 text-sm bg-white border border-violet-200 rounded-lg text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-violet-500 transition-all outline-none shadow-sm"
                        />
                    </div>
                )}
            </div>

            {/* Content Section Header */}
            <div className="mt-8 pt-6 border-t border-slate-100 flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center text-blue-600 shrink-0">
                    <FileText className="w-6 h-6" />
                </div>
                <h2 className="text-xl font-bold text-slate-800">{t.contentLabel}</h2>
            </div>

            {/* 目标受众 */}
            <div>
               <label className="block text-sm font-semibold text-slate-700 mb-2 flex items-center gap-2">
                   <Users className="w-4 h-4 text-blue-500" />
                   {t.targetAudience}
               </label>
               <input 
                  type="text" 
                  value={config.targetAudience || ''}
                  onChange={(e) => updateConfig('targetAudience', e.target.value)}
                  placeholder={t.targetAudiencePlaceholder}
                  className="w-full p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-blue-500 focus:bg-white transition-all shadow-inner"
               />
            </div>

            <div>
               <label className="block text-sm font-semibold text-slate-700 mb-2">{t.pageCount}</label>
               <div className="relative w-32">
                 <input 
                    type="number" 
                    value={config.pageCount}
                    onChange={(e) => updateConfig('pageCount', parseInt(e.target.value) || 1)}
                    min="1"
                    max="30"
                    className="w-full pl-4 pr-4 py-3 bg-slate-50 border-0 rounded-xl font-semibold text-slate-800 focus:ring-2 focus:ring-blue-500"
                 />
               </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">{t.contentLabel.split(' ')[2] || "输入内容"}</label>
              <textarea
                value={config.content}
                onChange={(e) => updateConfig('content', e.target.value)}
                placeholder={t.contentPlaceholder}
                className="w-full h-40 p-4 bg-slate-50 border-0 rounded-xl text-slate-700 placeholder:text-slate-400 focus:ring-2 focus:ring-blue-500 focus:bg-white transition-all resize-none shadow-inner"
              />
            </div>

            <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">{t.uploadLabel}</label>
                <div className="flex flex-wrap gap-4 items-center">
                    <input 
                        type="file" 
                        ref={fileInputRef}
                        onChange={handleFileChange}
                        className="hidden"
                        accept="image/*,application/pdf"
                    />
                    <button 
                        onClick={handleFileClick}
                        className="flex items-center gap-2 px-6 py-3 bg-white border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-50 hover:border-slate-300 transition-all shadow-sm"
                    >
                        <Upload className="w-5 h-5" />
                        <span>{t.uploadButton}</span>
                    </button>
                    
                    {config.uploadedFile && (
                        <div className="flex items-center gap-2 px-4 py-3 bg-green-50 text-green-700 rounded-xl border border-green-100 animate-fade-in">
                            <CheckCircle2 className="w-4 h-4" />
                            <span className="text-sm font-medium truncate max-w-[200px]">{config.uploadedFile.name}</span>
                            <button 
                                onClick={clearFile}
                                className="ml-1 p-1 hover:bg-green-100 rounded-full transition-colors"
                            >
                                <X className="w-3 h-3 text-green-600" />
                            </button>
                        </div>
                    )}
                </div>
                <p className="mt-2 text-xs text-slate-400 flex items-center gap-1">
                    <Sparkles className="w-3 h-3 text-blue-400" /> 
                    {t.uploadHint}
                </p>
            </div>
        </div>

        <div className="mt-10 pt-6 border-t border-slate-100">
          <button 
            onClick={onGenerate}
            disabled={isButtonDisabled}
            className="w-full bg-violet-600 hover:bg-violet-700 disabled:bg-slate-300 disabled:cursor-not-allowed text-white text-lg font-bold py-4 rounded-xl shadow-lg shadow-violet-200 flex items-center justify-center gap-3 transition-transform hover:scale-[1.01] active:scale-[0.99]"
          >
            {isGenerating ? (
                <>
                    <Loader2 className="w-6 h-6 animate-spin" />
                    {t.generating}
                </>
            ) : (
                <>
                    <Sparkles className="w-6 h-6" />
                    {!apiKey ? t.apiKeyRequired : t.generateButton}
                </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
};

const EditableText = ({ value, onChange, className, isTextarea = false, placeholder }) => {
    const safeValue = normalizeContent(value);

    if (isTextarea) {
        return (
            <textarea
                value={safeValue}
                onChange={(e) => onChange(e.target.value)}
                className={`w-full bg-transparent border border-transparent hover:border-slate-300 focus:border-violet-500 rounded-lg p-2 focus:bg-white focus:ring-0 transition-all outline-none resize-none ${className}`}
                placeholder={placeholder}
                rows={Math.max(3, safeValue.split('\n').length)}
            />
        );
    }
    return (
        <input
            type="text"
            value={safeValue}
            onChange={(e) => onChange(e.target.value)}
            className={`w-full bg-transparent border border-transparent hover:border-slate-300 focus:border-violet-500 rounded-lg px-2 py-1 focus:bg-white focus:ring-0 transition-all outline-none ${className}`}
            placeholder={placeholder}
        />
    );
};

const ResultStep = ({ resultData, setResultData, onReset, config, t, language, apiKey }) => {
  const [generatingPages, setGeneratingPages] = useState({}); 
  const [deleteConfirmIndex, setDeleteConfirmIndex] = useState(null); 
  const [warningIndex, setWarningIndex] = useState(null); 

  const handlePageChange = (index, field, value) => {
    const newPages = [...resultData.pages];
    newPages[index] = { ...newPages[index], [field]: value };
    setResultData({ ...resultData, pages: newPages });
  };
  
  const handleDeletePage = (indexToDelete) => {
    const remainingPages = resultData.pages.filter((_, index) => index !== indexToDelete);
    const reindexedPages = remainingPages.map((page, index) => ({
        ...page,
        page: index + 1
    }));
    setResultData({ ...resultData, pages: reindexedPages });
    setDeleteConfirmIndex(null); 
  };

  const handleMovePage = (index, direction) => {
      const newPages = [...resultData.pages];
      if (direction === -1 && index === 0) return; 
      if (direction === 1 && index === newPages.length - 1) return; 
      const targetIndex = index + direction;
      [newPages[index], newPages[targetIndex]] = [newPages[targetIndex], newPages[index]];
      const reindexedPages = newPages.map((page, idx) => ({ ...page, page: idx + 1 }));
      setResultData({ ...resultData, pages: reindexedPages });
  };

  const handleGlobalStyleChange = (field, value) => {
      setResultData({
          ...resultData,
          globalStyle: { ...resultData.globalStyle, [field]: value }
      });
  };

  const handleTopicChange = (value) => {
      setResultData({ ...resultData, topic: value });
  };

  const handleAddPage = () => {
    const newPageNum = resultData.pages.length + 1;
    const newPage = {
      page: newPageNum,
      title: "", 
      corePoints: "",
      visualElements: "",
      layoutDesign: ""
    };
    setResultData({
      ...resultData,
      pages: [...resultData.pages, newPage]
    });
  };

  const handleGeneratePageContent = async (index) => {
    const page = resultData.pages[index];
    if (!page.title.trim()) {
        setWarningIndex(index);
        setTimeout(() => setWarningIndex(null), 3000);
        return;
    }

    setGeneratingPages(prev => ({ ...prev, [index]: true }));

    try {
        const generatedContent = await generatePageContent(
            config, 
            page.title, 
            page.corePoints, 
            resultData.topic, 
            resultData.globalStyle,
            language,
            apiKey
        );
        
        const newPages = [...resultData.pages];
        newPages[index] = {
            ...newPages[index],
            ...generatedContent
        };
        setResultData({ ...resultData, pages: newPages });
    } catch (error) {
        console.error("Page Gen Error:", error);
        alert("Failed to generate page content.");
    } finally {
        setGeneratingPages(prev => ({ ...prev, [index]: false }));
    }
  };

  const handleDownload = () => {
    let content = `TOPIC: ${resultData.topic}\n\n`;
    content += `=== GLOBAL STYLE ===\n`;
    content += `Title: ${resultData.globalStyle.title}\n`;
    content += `Description: ${resultData.globalStyle.content}\n\n`;
    content += `==================================================\n\n`;

    resultData.pages.forEach((page, index) => {
      content += `Page ${page.page}: ${page.title}\n\n`;
      content += `[${t.corePoints}]\n${page.corePoints}\n\n`;
      content += `[${t.visualElements}]\n${page.visualElements}\n\n`;
      content += `[${t.layoutDesign}]\n${page.layoutDesign}\n\n`;
      content += `--------------------------------------------------\n\n`;
    });

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${resultData.topic.substring(0, 20)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 animate-fade-in-up">
      
      {/* Header Result */}
      <div className="mb-8 flex flex-col md:flex-row md:justify-between md:items-end gap-4">
        <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
                 <Sparkles className="w-4 h-4 text-violet-500" />
                 <div className="text-sm font-bold text-slate-400 uppercase tracking-wider">{t.resultTitle}</div>
            </div>
            <EditableText 
                value={resultData.topic} 
                onChange={handleTopicChange} 
                className="text-3xl font-extrabold text-slate-900 leading-tight"
            />
        </div>
        <button 
            onClick={handleDownload}
            className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg font-medium shadow-md transition-colors whitespace-nowrap"
        >
            <Download className="w-4 h-4" />
            {t.downloadButton}
        </button>
      </div>

      {/* Global Style Card */}
      <div className="bg-slate-900 rounded-2xl p-6 mb-10 shadow-xl border border-slate-800 relative overflow-hidden group">
        <div className="absolute top-0 right-0 w-64 h-64 bg-violet-500 rounded-full blur-[100px] opacity-20 group-hover:opacity-30 transition-opacity"></div>
        <div className="relative z-10">
            <div className="flex items-center gap-2 mb-4 text-violet-300">
                <Palette className="w-5 h-5" />
                <h3 className="font-bold text-lg">
                    {config.includePersona ? t.personaStyleTitle : resultData.globalStyle.title}
                </h3>
            </div>
            <div className="bg-slate-800/50 p-2 rounded-xl border border-slate-700/50 backdrop-blur-sm">
                <EditableText
                    isTextarea
                    value={resultData.globalStyle.content}
                    onChange={(val) => handleGlobalStyleChange('content', val)}
                    className="text-slate-300 leading-relaxed text-sm focus:text-slate-900 focus:bg-white"
                />
            </div>
        </div>
      </div>

      {/* Pages List */}
      <div className="space-y-8">
        {resultData.pages.map((page, index) => (
            <div key={index} className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden hover:shadow-lg transition-shadow duration-300 group">
                {/* Page Header */}
                <div className="px-6 py-4 border-b border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-50/50">
                    <div className="flex items-center gap-3 w-full">
                        <span className="text-2xl font-black text-violet-600 font-mono whitespace-nowrap">Page {page.page}</span>
                        <div className="w-px h-6 bg-slate-300 hidden md:block"></div>
                        <div className="flex-1">
                             <EditableText 
                                value={page.title} 
                                onChange={(val) => handlePageChange(index, 'title', val)}
                                className={`text-xl font-bold transition-colors ${warningIndex === index ? 'text-red-500 placeholder:text-red-300' : 'text-slate-800 placeholder-slate-400'}`}
                                placeholder={warningIndex === index ? t.enterTitleWarning : t.pageTitlePlaceholder}
                             />
                        </div>
                    </div>
                    
                    <div className="flex items-center gap-2">
                        {/* Move Up/Down Buttons */}
                        <div className="flex items-center mr-2 border-r border-slate-200 pr-2 gap-1">
                            <button
                                onClick={() => handleMovePage(index, -1)}
                                disabled={index === 0}
                                className="p-1.5 rounded-lg text-slate-400 hover:text-violet-600 hover:bg-violet-50 disabled:opacity-30 disabled:hover:bg-transparent disabled:hover:text-slate-400 transition-all"
                                title={t.moveUp}
                            >
                                <ArrowUp className="w-4 h-4" />
                            </button>
                            <button
                                onClick={() => handleMovePage(index, 1)}
                                disabled={index === resultData.pages.length - 1}
                                className="p-1.5 rounded-lg text-slate-400 hover:text-violet-600 hover:bg-violet-50 disabled:opacity-30 disabled:hover:bg-transparent disabled:hover:text-slate-400 transition-all"
                                title={t.moveDown}
                            >
                                <ArrowDown className="w-4 h-4" />
                            </button>
                        </div>

                        {/* Single Page Generation Button */}
                        <button 
                            onClick={() => handleGeneratePageContent(index)}
                            disabled={generatingPages[index]}
                            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-all whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed ${
                                warningIndex === index 
                                ? 'bg-red-100 text-red-600 animate-pulse' 
                                : 'bg-violet-100 hover:bg-violet-200 text-violet-700'
                            }`}
                            title="根据标题自动生成内容"
                        >
                            {generatingPages[index] ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                            {generatingPages[index] ? t.generatingButton : warningIndex === index ? t.enterTitleWarning : t.aiGenerateButton}
                        </button>
                        
                        {/* Delete Button (Double Click Logic) */}
                        <button
                            onClick={() => {
                                if (deleteConfirmIndex === index) {
                                    handleDeletePage(index);
                                } else {
                                    setDeleteConfirmIndex(index);
                                    setTimeout(() => setDeleteConfirmIndex(null), 3000); // Auto reset
                                }
                            }}
                            className={`p-2 rounded-lg transition-all duration-200 flex items-center gap-2 ${
                                deleteConfirmIndex === index 
                                ? "bg-red-500 text-white hover:bg-red-600 shadow-sm px-3" 
                                : "text-slate-400 hover:text-red-500 hover:bg-red-50"
                            }`}
                            title={deleteConfirmIndex === index ? "Again to Confirm" : "Delete Page"}
                        >
                            <Trash2 className="w-4 h-4" />
                            {deleteConfirmIndex === index && <span className="text-xs font-bold whitespace-nowrap">{t.deleteConfirm}</span>}
                        </button>
                    </div>
                </div>

                <div className="p-6 space-y-6">
                    {/* Core Points (was Summary) */}
                    <div>
                        <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">{t.corePoints}</h4>
                        <div className="bg-slate-50 p-2 rounded-xl border border-slate-100">
                             <EditableText 
                                isTextarea
                                value={page.corePoints} 
                                onChange={(val) => handlePageChange(index, 'corePoints', val)}
                                className="text-slate-700 leading-relaxed text-base min-h-[80px]"
                                placeholder={t.corePointsPlaceholder}
                             />
                        </div>
                    </div>

                    {/* Visual Elements (was Image Prompt) - MOVED TO MIDDLE */}
                    <div className="bg-slate-900 rounded-xl p-3 border border-slate-800">
                         <div className="flex items-center gap-2 mb-2 text-green-400 px-2">
                            <ImageIcon className="w-4 h-4" />
                            <h4 className="font-bold text-xs uppercase tracking-wider flex items-center gap-2">
                                {t.visualElements}
                                <span className="text-[10px] bg-green-800 text-green-200 px-1 rounded">{t.generatedByGemini}</span>
                            </h4>
                        </div>
                        <EditableText 
                            isTextarea
                            value={page.visualElements} 
                            onChange={(val) => handlePageChange(index, 'visualElements', val)}
                            className="text-green-300 font-mono text-sm leading-relaxed break-words focus:text-slate-900 focus:bg-white min-h-[60px]"
                            placeholder={t.visualElementsPlaceholder}
                        />
                    </div>

                    {/* Layout Design (was Layout Guide) - MOVED TO BOTTOM */}
                    <div className="bg-blue-50 rounded-xl p-3 border border-blue-100">
                        <div className="flex items-center gap-2 mb-2 text-blue-700 px-2">
                            <Layout className="w-5 h-5" />
                            <h4 className="font-bold text-sm">{t.layoutDesign}</h4>
                        </div>
                        <EditableText 
                            isTextarea
                            value={page.layoutDesign} 
                            onChange={(val) => handlePageChange(index, 'layoutDesign', val)}
                            className="text-slate-700 text-sm leading-relaxed focus:bg-white/90 min-h-[60px]"
                            placeholder={t.layoutDesignPlaceholder}
                        />
                    </div>
                </div>
            </div>
        ))}

        {/* Add Page Button */}
        <button
            onClick={handleAddPage}
            className="w-full py-4 border-2 border-dashed border-slate-300 rounded-2xl flex items-center justify-center gap-2 text-slate-500 hover:text-violet-600 hover:border-violet-400 hover:bg-violet-50 transition-all font-medium"
        >
            <Plus className="w-5 h-5" />
            {t.addPage}
        </button>
      </div>

      {/* Footer Action */}
      <div className="mt-10 flex justify-center">
        <button 
            onClick={onReset}
            className="text-slate-500 hover:text-violet-600 font-medium flex items-center gap-2 px-6 py-3 rounded-xl hover:bg-white transition-all"
        >
            重新设计一个专案 <ArrowRight className="w-4 h-4" />
        </button>
      </div>

    </div>
  );
};

export default function App() {
  const [step, setStep] = useState('input'); // input, result
  const [isGenerating, setIsGenerating] = useState(false);
  const [language, setLanguage] = useState('zh'); // 'zh' or 'en'
  const [config, setConfig] = useState({
      styleDesc: "",
      pageCount: 5,
      content: "",
      uploadedFile: null,
      includePersona: false,
      customPersona: "", // 存储自定义角色
      strictExtraction: false, 
      addIntro: false,        // 新增：导入开关
      addQuestions: false,    // 新增：提问开关
      addInteraction: false,  // 新增：互动开关
      addConclusion: false,   // 新增：结语开关
      targetAudience: "" ,
      structureType: 'keypoint', 
      layoutStyle: 'traditional' 
  });
  const [resultData, setResultData] = useState(null);

  // --- API Key State Management with LocalStorage ---
  const [apiKey, setApiKey] = useState(() => {
      // Check localStorage on initial load
      if (typeof window !== 'undefined') {
          return localStorage.getItem('gemini_api_key') || '';
      }
      return '';
  });

  // Save to localStorage whenever apiKey changes
  useEffect(() => {
      if (typeof window !== 'undefined') {
          localStorage.setItem('gemini_api_key', apiKey);
      }
  }, [apiKey]);

  const t = TRANSLATIONS[language];

  const updateConfig = (key, value) => {
      setConfig(prev => ({ ...prev, [key]: value }));
  };

  const handleGenerate = async () => {
    if (!apiKey) {
        alert(language === 'zh' ? "请输入 API Key" : "Please enter API Key");
        return;
    }

    setIsGenerating(true);
    
    try {
        // Pass apiKey to generator
        const generatedData = await generateWithGemini(config, language, apiKey);
        setResultData(generatedData);
        setStep('result');
        window.scrollTo(0, 0);
    } catch (error) {
        console.error("Failed to generate:", error);
        alert(language === 'zh' 
            ? `生成失败: ${error.message}` 
            : `Generation failed: ${error.message}`);
    } finally {
        setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] font-sans selection:bg-violet-200 selection:text-violet-900">
      <Header language={language} setLanguage={setLanguage} t={t} />
      
      <main>
        {step === 'input' && (
            <InputStep 
                config={config} 
                updateConfig={updateConfig} 
                onGenerate={handleGenerate} 
                isGenerating={isGenerating}
                t={t}
                language={language}
                apiKey={apiKey}
                setApiKey={setApiKey}
            />
        )}
        {step === 'result' && resultData && (
            <ResultStep 
                resultData={resultData} 
                setResultData={setResultData}
                onReset={() => setStep('input')}
                config={config} 
                t={t}
                language={language}
                apiKey={apiKey}
            />
        )}
      </main>

      <footer className="py-8 text-center text-slate-400 text-sm">
        {t.footerText}
      </footer>
    </div>
  );
}
